### ISSUE TITLE
Demandes d'évaluations qui ne fonctionne pas

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#1]
Le problème le plus impactant est le non fonctionnement des demandes d'évaluations et de feedbacks à tout niveau (dans les SAés, les compétences, les stages...).

**Comment by jgribonvald** [comment]
@olivier-gerbe on a un pb où il est impossible d'insérer dans la table vector car la colonne a5 fait moins de 360 caractères. Si on augmente la taille de la colonne ça passe. Saurais tu de quoi vient ce pb ? de votre côté il y a eu un changement opéré sur la BD ou vous étes toujours en varchar 256?

**Comment by olivier-gerbe** [comment]
Depuis 1.4 on est passé à varchar(5000) pour a5 car j'y stocke un gros son

**Comment by jgribonvald** [comment]
@olivier-gerbe Il n'y a pas eu de commit sur git montrant ce changement. Et là on teste en 1.3.5 de kapc. Tu as la possibilité de fournir un export du schéma de la BDD ?

```sql

mysqldump --databases karuta --no-data > my_schema.sql
```
