### ISSUE TITLE
Bug dû à un problème de latence ? - portfolio étudiant

### ISSUE THREAD

**Issue by MattLUnLille** [avenirs-esr/GT-Test#10]
Bonjour,

Côté portfolio étudiant, j'ai connu à l'instant un bug qui "figeait" l’espace de quelques secondes le menu déroulant - dans "Mes bilans par compétences" -> "BUT Qualité Logistique Industrielle et Organisation" - et m'empêchait d'aller sur la page en question ou de cliquer sur une autre entrée de ce même menu.
Par ailleurs, le chargement des différents contenus présents sur les pages n'était pas complet pendant un temps certain (cf. capture d'écran) - apparemment cela est passé et le problème résolu.
![Capture d’écran 2023-07-21 150618](https://github.com/avenirs-esr/GT-Test/assets/139477155/fdc77b3b-170f-4554-80ac-d1f4c9deeeef)

**Comment by AdrienPrugnaud** [comment]
Bonjour,
On peut avoir quelques problèmes de latence en fonction de la connexion ou lors d'une première ouverture du portfolio. Normalement ce ralentissement n'est pas fréquent.

**Comment by MattLUnLille** [comment]
Merci de ta réponse, @AdrienPrugnaud
