### ISSUE TITLE
Demande de feedback enseignant depuis le portfolio étudiant non comptabilisée dans le portfolio enseignant - formation BUT QLIO portfolio étudiant

### ISSUE THREAD

**Issue by MattLUnLille** [avenirs-esr/GT-Test#11]
Bonjour,

Dans le portfolio côté étudiant, après avoir sélectionné la formation du BUT QLIO, j'ai réussi à importer une SAé dans "Mes actions et traces" -> "Mes actions" -> "Mes SAés" -> "SAé 3.01 Développement d'une application".
Dans cette SAé, j'ai fait une demande de feedback - partie 6.
Or, cette demande semble ne pas apparaître du côté enseignant, pouvez-vous le confirmer ?
Je vous en remercie d'avance (cf. pj) : 
![Capture d’écran 2023-07-21 164938](https://github.com/avenirs-esr/GT-Test/assets/139477155/d7e8f866-f146-4d1e-bdbc-592135420dcd)
![Capture d’écran 2023-07-21 164424](https://github.com/avenirs-esr/GT-Test/assets/139477155/17a86031-d89a-46cc-b25c-ebe28a920033)
![Capture d’écran 2023-07-21 164440](https://github.com/avenirs-esr/GT-Test/assets/139477155/39fed4b8-47a1-4f4b-b74f-a7679dff65a0)

**Comment by AdrienPrugnaud** [comment]
Ah je vois que la SAé créée était en Informatique alors que l'étudiant et l'enseignant étaient rattachés seulement en QLIO ce qui a causé le problème. 
Je départage les portfolios d'informatique à l'enseignant ce qui devrait éviter le problème

**Comment by MattLUnLille** [comment]
Ah, je comprends mieux ...
Je retesterai derrière pour vérifier la bonne résolution de ce bug.
A part bien vérifier que c'est la bonne compétence rattachée à la bonne formation et signaler le problème, on ne peut rien faire d'autre pour le résoudre à notre niveau côté étudiant et/ou enseignant ?

**Comment by AdrienPrugnaud** [comment]
Ces paramétrages se passent au niveau "admin" mais c'est souvent au niveau des étudiants et enseignants que sont constatés ces problèmes lors de l'utilisation de leur portfolio. Par exemple ce problème peut venir d'informations incorrectes dans les csv d'association des comptes enseignants à une formation
