### ISSUE TITLE
Bug "Erreur de sauvegarde" affiché dans le portfolio étudiant - lié à une action en particulier ?

### ISSUE THREAD

**Issue by MattLUnLille** [avenirs-esr/GT-Test#12]
Bonjour, 

En me connectant pour la première fois du jour sur le portfolio étudiant ce matin, en demandant l'envoi du feedback en entrant mon adresse mail, j'ai ce message : "Oups! Erreur de sauvegarde ..." qui s'affiche : 
![Capture d’écran 2023-08-22 100306](https://github.com/avenirs-esr/GT-Test/assets/139477155/7556c91e-6960-4877-a39c-5a21486d5774)

Cela ne faisait que 1 à 2 minutes que j'étais connecté au portfolio étudiant, est-ce que ce serait lié à cette action de demande d'envoi de mail spécifique pour qu'un tel message s'affiche ?
Je vous remercie d'avance pour votre réponse pour la bonne résolution de ce bug.

**Comment by AdrienPrugnaud** [comment]
Est-ce que l'adresse mail entrée était la même que celle utilisée dans le portfolio ?

**Comment by MattLUnLille** [comment]
Oui, c'est vraisemblablement dû à l'action d'utiliser la même adresse mail que le message est ainsi apparu, en effet.
Il faudrait songer à modifier le message d'erreur trop impersonnel pour ce type de bug.
