### ISSUE TITLE
Bug "évalutation stage et alternance" "à évaluer" demandé en portfolio étudiant et non-répondu du côté enseignant.

### ISSUE THREAD

**Issue by MattLUnLille** [avenirs-esr/GT-Test#14]
Bonjour,

Je m'aperçois que la demande d' "évaluation par mon ou mes enseignant(s)" - dans "Mes actions et traces" -> "Mes actions" -> "Mes stages et alternances" -> "Intitulé de mon stage ou de mon alternance (à modifier)" - effectuée le 21 Juillet à 16H01 côté étudiant semble ne pouvoir être évaluée par l'enseignant depuis son portfolio en cliquant sur les jumelles : 

![Capture d’écran 2023-08-22 102630](https://github.com/avenirs-esr/GT-Test/assets/139477155/c47124bf-ad8b-4000-8e58-2564754932f8)
![Capture d’écran 2023-08-22 102145](https://github.com/avenirs-esr/GT-Test/assets/139477155/95061ca4-33be-4d5a-94d0-1dc58de5a07f)
![Capture d’écran 2023-08-22 102301](https://github.com/avenirs-esr/GT-Test/assets/139477155/527e52dc-fb88-4675-9c85-6f6e5ffe0b7e)
![Capture d’écran 2023-08-22 102318](https://github.com/avenirs-esr/GT-Test/assets/139477155/32bb3b4e-2602-40ed-aee1-1d5549993ebd)

Merci d'avance pour la bonne résolution de ce problème

**Comment by AdrienPrugnaud** [comment]
Avec la nouvelle version de 1.3.5 le problème est corrigé, il faudra retester pour confirmer que tout fonctionne correctement

**Comment by MattLUnLille** [comment]
Bien reçu, je le ferai dès que possible.
