### ISSUE TITLE
Bug envoi mail - demander une évaluation par un pair/à mon tuteur pro - portfolio étudiant

### ISSUE THREAD

**Issue by MattLUnLille** [avenirs-esr/GT-Test#15]
Bonjour,

Peut-être est-ce un bug temporaire : lorsque je veux envoyer un mail pour demander l'évaluation par un pair du côté portfolio étudiant, et ce alors que je viens juste de me connecter à mon profil étudiant donc, j'ai un message d'erreur rouge qui s'affiche.
Et même en ayant cliqué, l'action ne s'effectue pas vu que je ne reçois aucun mail de mon côté : 
![Capture d’écran 2023-09-04 121224 - bug envoi mail KAPC+1 3 5](https://github.com/avenirs-esr/GT-Test/assets/139477155/05470855-a3ae-4fe1-9d55-7e26a99b4af8)

Je vous remercie d'avance pour sa bonne résolution, bon courage à vous

**Comment by MattLUnLille** [comment]
Edit : alors, cela fonctionne, mais le message d'erreur reste. Il faudrait l'expliciter si possible.
Cela doit être lié au fait que j'utilise le rôle "pair" de fait en passant par mon adresse qui est la même utilisée pour me connecter en étant qu'étudiant, et donc il est retenu ce rôle de "pair" pour voir le portfolio.

**Comment by AdrienPrugnaud** [comment]
Exactement, on ne peut pas s'auto-demander une évaluation en tant que pair avec une adresse déjà utilisée dans Karuta.

**Comment by MattLUnLille** [comment]
Peut-on utiliser une autre adresse, mais qui serait non CASifiée, pour notamment tester cette action sans rencontrer de problème de visibilité ?

**Comment by AdrienPrugnaud** [comment]
Oui c'est possible, par exemple sur le serveur de démo Avenir(s) la connexion étudiant et enseignant passent par un CAS et la fonction de partage fonctionne correctement avec des adresses non référencées gmail,hotmail...
