### ISSUE TITLE
Trace non dispo pour les enseignants

### ISSUE THREAD

**Issue by Isamath** [avenirs-esr/GT-Test#18]
Je viens d'ajouter des preuves dans une saé, les jumelles fonctionnent coté etudiant mais pas coté enseignant
![Capture1](https://github.com/avenirs-esr/GT-Test/assets/105660222/fa14173c-6b8e-47a5-a697-5c86de98ceac)

**Comment by Isamath** [comment]
@olivier 
ETU-1-4 (saé = première saé) les 3 traces sont visibles et existent dans le portfolio de l'étudiant
sur ENS-1-4 les traces ne s'ouvrent pas dans la saé à évaluer

**Comment by AdrienPrugnaud** [comment]
@giraudin @olivier-gerbe @Isamath j'ai la même chose : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/ad928b9d-dc68-42e9-a234-3d2624571321)

**Comment by giraudin** [comment]
@marusmb tu peux tester et répondre à Adrien ?

**Comment by marusmb** [comment]
Le problème n'est pas résolu pour le quatre types de traces, en revanche cela fonctionne bien lors de l'autoévaluation de l'étudiant ainsi que pour les évaluations du pair et du tuteur pro.
![image](https://github.com/avenirs-esr/GT-Test/assets/160909485/731a1ad8-1607-461b-98a4-ce0716900366)

**Comment by olivier-gerbe** [comment]
@marusmb Je pourrai avoir le lien pour le site et les infos pour voir car nous n'arrivons pas à reproduire.
Merci.
Olivier

**Comment by marusmb** [comment]
@olivier-gerbe 
site : https://karuta-porfolio.univ-smb.fr
SAé : GCCD évaluateur étudiant
compte enseignant Karuta identifiant = mot de passe : logens21
SAés à évaluer, il n'y en a qu'une
compte étudiant Karuta identifiant = mot de passe : logetu21

**Comment by olivier-gerbe** [comment]
Pas sûr que la version de karuta-backend soit la bonne
 Karuta-backend : 2.6.5 (2024-01-22T07:44:07Z)

**Comment by AdrienPrugnaud** [comment]
@olivier-gerbe j'ai la bonne version du back-end mais j'ai le même bug que Michel : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/6407c9d4-233e-4f4a-b719-2ab636d4b07b)

![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/7d08f7af-c99c-47cd-8f77-3b0b3aec6f18)

**Comment by olivier-gerbe** [comment]
Problème de version
![Capture d’écran, le 2024-06-17 à 12 27 30](https://github.com/avenirs-esr/GT-Test/assets/8060484/fa7c1368-3d5e-4b23-b41b-e3338e4d7e63)

Bizarre. Elles sont le même numéro et pas la même date.
J'ai récupéré votre version sur sonotype et cela ne marche pas non plus pour moi

**Comment by AdrienPrugnaud** [comment]
@jgribonvald passe en debug

**Comment by AdrienPrugnaud** [comment]
Corrigé avec la version 2.6.7 du backend

**Comment by AdrienPrugnaud** [comment]
Fait, à fermer @jgribonvald
