### ISSUE TITLE
Impossible aux étudiants et aux enseignants hors compte universitaire de modifier leur mot de passe 

### ISSUE THREAD

**Issue by marusmb** [avenirs-esr/GT-Test#19]
Pour les étudiants et les enseignants utilisant la connexion hors compte universitaire, il n'est pas possible de modifier le mot de passe.
Quand on clique sur le nom de la personne connectée en haut à droite de la page, il ne se passe rien. Le seul cas où l'on a la possibilité de modifier le mot de passe est quand on est connecté avec compte administrateur universitaire.

**Comment by isabelle-roy** [comment]
Paramétrage de Karuta par l'université. Pas un bug.
