### ISSUE TITLE
Erreur création conseiller via fichiers CSV

### ISSUE THREAD

**Issue by marusmb** [avenirs-esr/GT-Test#20]
En utilisant le fichier CSV modèle disponible dans la page "Formulaires Projet de vie" de Karuta, L'application reste bloquée sur l'exécution du script. Je me suis rendu compte que le model_code dans le fichier CSV est kapc/9Aprojetpro/3conseillers.batch-creer-conseillers, alors que le chemin d'accès au répertoire est kapc/9Aprojetpro/3conseillers.batch-creer-conseillers-pp.
J'ai des essais en rajoutant le "-pp" dans le fichier csv, ce qui corrige le problème.

**Comment by isabelle-roy** [comment]
Ok, problème identifié, je vais corriger aujourd'hui et vous envoyer le nouveau modèle de fichier csv.
Isabelle

**Comment by isabelle-roy** [comment]
Voici la nouvelle version du portfolio Formulaires Projet de vie :
[portfolio-Formulaires-Projet-de-vie.zip](https://github.com/avenirs-esr/GT-Test/files/14423027/portfolio-Formulaires-Projet-de-vie.zip)

**Comment by AdrienPrugnaud** [comment]
Testé, cela m'a l'air de fonctionner, à confirmer par @marusmb

**Comment by marusmb** [comment]
Je confirme, problème résolu.
