### ISSUE TITLE
Erreur suppression de conseillers via fichier CSV

### ISSUE THREAD

**Issue by marusmb** [avenirs-esr/GT-Test#21]
En utilisant le fichier CSV de l'application, la suppression n'est pas réalisée avec comme message d'erreur : "Either model_code is not defined, or that the CSV file wasn't parsed properly (check separators)" 
J'ai rajouté dans la case de la première ligne seconde colonne le caractère "a". Avec cette modification la suppression c'est bien réalisée mais uniquement sur le premier conseiller, les lignes suivantes ont été ignorées. 
[csv supprimer conseillers projet de vie.csv](https://github.com/avenirs-esr/GT-Test/files/14407570/csv.supprimer.conseillers.projet.de.vie.csv)

**Comment by isabelle-roy** [comment]
Ok, problème identifié, je vais corriger aujourd'hui et vous envoyer le nouveau modèle de fichier csv.
Isabelle

**Comment by isabelle-roy** [comment]
Voici la nouvelle version du portfolio Formulaires Projet de vie :
[portfolio-Formulaires-Projet-de-vie.zip](https://github.com/avenirs-esr/GT-Test/files/14423039/portfolio-Formulaires-Projet-de-vie.zip)

**Comment by AdrienPrugnaud** [comment]
Testé cela m'a l'air bon, à confirmer par @marusmb

**Comment by marusmb** [comment]
J'ai refais des tests complets suppression par formulaire ou par csv, c'est bon.
