### ISSUE TITLE
Impossible de supprimer un portfolio projet de vie à un étudiant qui a déja un portfolio APC

### ISSUE THREAD

**Issue by giraudin** [avenirs-esr/GT-Test#22]
1) J'ai créé un portfolio APC pour Etudiant1 en GEII cohorte 2023 (option authentification externe choisie)
2) J'ai créé un portfolio Mon projet de vie pour Etudiant1 GEII cohorte 2023 (pas d'option authentification externe possible ????)
3) L'étudiant voit bien ses deux portfolios
4) Avec le formulaire de suppression, impossible de supprimer le portfolio Mon projet de vie

**Comment by giraudin** [comment]
Et quand il rentre dans un portfolio ex APC il ne voit pas son portfolio Projet de Vie

**Comment by isabelle-roy** [comment]
1. Il n'y a pas de question au sujet de l'authentification dans le module projet de vie parce que le compte a été créé dans le batch du module APC.
2. Effectivement, après démonstration par M. Marquette, ça fonctionne chez nous mais pas chez vous : M. Marquette va nous fournir un compte admin pour qu'on puisse faire des tests chez vous. À suivre.

**Comment by olivier-gerbe** [comment]
Après vérification, le serveur de test https://portfolio.univ-smb.fr n'a pas les dernières versions de Karuta. Prière de faire les mises à jour.

**Comment by isabelle-roy** [comment]
Allo Éric, après avoir fait les mises à jour du frontend n'oublie pas de vider ta cache avant de tester à nouveau... Isabelle

**Comment by AdrienPrugnaud** [comment]
Cela m'a l'air bon, à confirmer par @giraudin

**Comment by giraudin** [comment]
@marusmb tu peux tester et confirmer ?

**Comment by marusmb** [comment]
Le problème est toujours présent. Ce qui est troublant c'est qu'en recommençant la suppression du portfolio projet de vie, j'ai eu le message ci-dessous mais le portefolio projet de vie est toujours opérationnel.
![image](https://github.com/avenirs-esr/GT-Test/assets/160909485/148318b0-b9c0-469b-a724-36e74945606a)

**Comment by olivier-gerbe** [comment]
@marusmb Est-ce que l'on peut avoir infos pour y accéder? Merci Olivier

**Comment by olivier-gerbe** [comment]
Je ne comprends. Il n'y a plus de portfolios pour testketu ni projet de vie ni APC d'où le message.

**Comment by marusmb** [comment]
Pourtant j'arrive toujours à accéder à ses portfolio.

J'ai pu ajouter des traces dans la section "Mes formations" du portfolio projet de vie depuis son portfolio de compétences.
Etudiant test avec un compte USMB id: testketu et mdp: JO9GcN5rh5hsY/
Je suis désolé mais je vais m'arrêter pour aujourd'hui, normalement je ne travaille pas le vendredi après-midi et j'ai un rendez-vous.
@olivier-gerbe 
![image](https://github.com/avenirs-esr/GT-Test/assets/160909485/8e1550f0-bce1-4a2f-ae87-8cb46b3ce151)

**Comment by olivier-gerbe** [comment]
Tes données sont vraiment bizarres. Voici les partages de testketu
![Capture d’écran, le 2024-06-15 à 12 05 57](https://github.com/avenirs-esr/GT-Test/assets/8060484/ab1edbfb-4ded-4dde-ae16-31a509ca39e8)

**Comment by AdrienPrugnaud** [comment]
@marusmb A retester avec la nouvelle livraison des zips

**Comment by marusmb** [comment]
C'est ok pour moi avec la version des zip du 20/06.

**Comment by AdrienPrugnaud** [comment]
@marusmb @jgribonvald A fermé

**Comment by marusmb** [comment]
@AdrienPrugnaud Je l'aurais fermée avec plaisir mais je n'en ai pas la possibilité

**Comment by AdrienPrugnaud** [comment]
Mince désolé (c'est Eric qui avait créé l'issue je n'avais pas fait attention) ! Ce sera Julien alors :)

**Comment by AdrienPrugnaud** [comment]
A fermer @jgribonvald
