### ISSUE TITLE
Mon projet de vie : ne pas afficher les codes des compétences dans la synthèse

### ISSUE THREAD

**Issue by giraudin** [avenirs-esr/GT-Test#23]
Normalement, les codes des compétences ne doivent pas s'afficher dans la synthèse. C'est bien ce qui avait était décidé et fait sur la version de prétest sur le serveur eportfolium mais dans la version livrée les codes des compétences s'affichent devant les libéllés. 

![image](https://github.com/avenirs-esr/GT-Test/assets/7628798/21cadc1a-f3f5-4870-91b6-97bbcf438737)

**Comment by isabelle-roy** [comment]
Corrigé (CSS)
Sera livré avec la prochaine version

**Comment by giraudin** [comment]
Merci !

Le 27 févr. 2024 à 20:06, Isabelle Roy a écrit :﻿

Corrigé

Sera livré avec la prochaine version

**Comment by isabelle-roy** [comment]
Vous avez reçu la nouvelle version en avril, est-ce que quelqu'un peut approuver et fermer l'issue ?

**Comment by giraudin** [comment]
@marusmb tu peux tester et approuver pour Isabelle si c'est bon ?

**Comment by marusmb** [comment]
Le problème est toujours présent.
![image](https://github.com/avenirs-esr/GT-Test/assets/160909485/d56e1edb-e693-4d33-99d4-f4e1545cae10)

**Comment by olivier-gerbe** [comment]
@marusmb idem infos pour voir. Merci

**Comment by olivier-gerbe** [comment]
Le serveur n'est pas à jour backend et css etc.

**Comment by AdrienPrugnaud** [comment]
Pour moi cela fonctionne : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/e06c1b50-ceb8-4ac7-9539-41434a9a15ee)

**Comment by AdrienPrugnaud** [comment]
@marusmb A retester avec une nouvelle livraison

**Comment by AdrienPrugnaud** [comment]
Pour ma part c'est bon : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/e17766b7-07e1-4074-bd84-2affdbce587c)

**Comment by AdrienPrugnaud** [comment]
A confirmer par @marusmb

**Comment by marusmb** [comment]
C'est ok pour moi avec la version des zip du 20/06.

**Comment by AdrienPrugnaud** [comment]
@marusmb @jgribonvald A fermé

**Comment by marusmb** [comment]
@AdrienPrugnaud comme pour la 23 je n'en ai pas la possibilité

**Comment by AdrienPrugnaud** [comment]
A fermer @jgribonvald
