### ISSUE TITLE
Mon projet de vie : modifier la page d'accueil du conseiller établissement

### ISSUE THREAD

**Issue by giraudin** [avenirs-esr/GT-Test#24]
Remplacer tout le texte sous le bandeau bleu et avant le bandeau Besoin d'aide 

par le texte suivant et l'image (en la réduisant) puis le texte sous l'image suivants 

### Aider nos apprenants à construire leur projet de vie (formation, professionnel, citoyen)

![image](https://github.com/avenirs-esr/GT-Test/assets/7628798/8135ae69-c2df-47d5-9175-8bef7bf2dcd4)

Répondez aux apprenants qui partagent leur portfolio "Mon projet de vie" avec vous. Grâce à vos retours et à ceux d'autres acteurs*, vous pouvez aider l'étudiant dans chacune des différentes rubriques de son portfolio qu'il souhaite partager, en toute confidentialité avec vous :

- Me connaître
- Explorer mon futur
- Faire mon bilan
- Bâtir mon projet
- Ma synthèse CV

_*Ces autres acteurs peuvent être des enseignants de leur formation, d'autres conseillers en orientation et insertion professionnelle de l'établissement ou des personnes externes à l'établissement (ex : un professionnel qui a suivi l'apprenant dans son stage, un proche, etc.)_

**Comment by isabelle-roy** [comment]
![accueil cons pp](https://github.com/avenirs-esr/GT-Test/assets/1541128/ff44cd99-093c-40c2-8132-d04f7c0ea5a3)

**Comment by giraudin** [comment]
Parfait !

Le 27 févr. 2024 à 20:44, Isabelle Roy a écrit :﻿
accueil.cons.pp.png (view on web)
