### ISSUE TITLE
Créer un nouveau modèle CGU et RGPD spécifique à Mon projet de vie

### ISSUE THREAD

**Issue by giraudin** [avenirs-esr/GT-Test#25]
A faire

**Comment by giraudin** [comment]
Toujours à faire en partant du RGPD actuel pour le portfolio de compétences (APC)

**Comment by giraudin** [comment]
@olivier-gerbe  vérifier que techniquement il y a bien l'appel de deux fichiers CGU RGPD différents

**Comment by olivier-gerbe** [comment]
@giraudin
il y a 2 fichiers. Un dans KPAC un dans Projet de vie

**Comment by giraudin** [comment]
ok merci.

**Comment by AdrienPrugnaud** [comment]
@jgribonvald A fermé stp
