### ISSUE TITLE
Mon projet de vie : dupliquer la page proxy aide étudiant pour le conseiller interne et l'adapter

### ISSUE THREAD

**Issue by giraudin** [avenirs-esr/GT-Test#26]
J'ai mis à jour la page proxy mon projet de vie pour l'étudiant. 
Afin de gagner du temps il faudrait la dupliquer pour le conseiller interne et l'adapter légèrement. 

Est-ce qu'on peut juste la dupliquer et recopier la métadonnée tag sémantique du pp conseiller à la place de celle de pp étudiant ?

**Comment by isabelle-roy** [comment]
Il y a déjà les deux pages Proxy, je ne comprends pas...
![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/82d75e84-5a28-4281-9a8f-85ecbe78191a)

**Comment by isabelle-roy** [comment]
À quel endroit tu as fait la maj, sur notre serveur ou le vôtre ? Dans le modèle ou l'instance ?

**Comment by giraudin** [comment]
Il s'agit de la page proxy PP étudiant travaillée sur la plateforme test
USMB qui a été bien renseignée.
Comment faire pour partir de cette page, la dupliquer afin de récupérer le
contenu pour la page PP conseiller. Ca ferait gagner beaucoup de temps.
Est-ce qu'on peut juste la dupliquer et changer uniquement le code
sémantique avec celui du PP conseiller ?

**Comment by isabelle-roy** [comment]
Je ne comprends pas, je ne vois pas de différence entre celle sur votre serveur et celle sur le nôtre ?
USMB :
![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/ac4c72e1-a5f0-45cf-8e66-5c3415eb63aa)

ePortfolium :
![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/351af6cc-db5f-4fef-bd58-7eecb8e24e91)

Tout de même, je fais la copie...

**Comment by giraudin** [comment]
Nous avons complété chaque zone déroulante  !!!

**Comment by isabelle-roy** [comment]
J'ai copié la page proxy étudiant (portfolio modèle) pour les conseillers. STP avise-moi quand tu as fini, je devrai remplacer le portfolio modèle sur notre serveur.

**Comment by isabelle-roy** [comment]
> Nous avons complété chaque zone déroulante  !!! ⁣Télécharger TypeApp pour Android ​Le 2 mars 2024, 15:25, à 15:25, Isabelle Roy ***@***.***> a écrit:
> […](#)
> Je ne comprends pas, je ne vois pas de différence entre celle sur votre serveur et celle sur le nôtre ? USMB : ![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/ac4c72e1-a5f0-45cf-8e66-5c3415eb63aa) ePortfolium : ![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/351af6cc-db5f-4fef-bd58-7eecb8e24e91) Tout de même, je fais la copie... -- Reply to this email directly or view it on GitHub: [#26 (comment)](https://github.com/avenirs-esr/GT-Test/issues/26#issuecomment-1974809505) You are receiving this because you authored the thread. Message ID: ***@***.***>

Oui j'avais pris une capture d'écran avec les sections fermées sinon ça ne rentrait pas verticalement dans une capture d'écran... pas de panique, si tu déplie le contenu est toujours là.

**Comment by isabelle-roy** [comment]
https://karuta-porfolio.univ-smb.fr/karuta/karuta/htm/karuta.htm
![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/2f2fcd42-48c8-4298-967b-dfefb6e4427f)
![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/3fea842c-2145-47ff-bf56-2a96dc55441b)

**Comment by giraudin** [comment]
C'est bon, la page proxy conseiller établissement est complétée

**Comment by isabelle-roy** [comment]
Ok transféré chez nous

**Comment by giraudin** [comment]
A tester par Michel @marusmb, Isabelle Mathieu, Adrien, etc.

**Comment by AdrienPrugnaud** [comment]
Nous avons bien une page proxy pour les conseillers.
Par contre si un conseiller et aussi enseignant évaluateurs il va seulement voir la rubrique "Aide" correspondant aux enseignants évaluateurs (il ne verra pas la rubrique "Aide" pour les conseillers).
@giraudin @isabelle-roy @marusmb

**Comment by AdrienPrugnaud** [comment]
Pour l'instant rien ne pourra être fait. **FAIT POUR LA 1.4**
On ne peut pas cumuler les rôles dans Karuta (on n'est pas supposé avoir 2 rôles pour un compte). 
Ainsi un enseignant ne pourra être et conseiller et enseignant

**Comment by isabelle-roy** [comment]
Pour la 1.4 on considère que un enseignant et un conseiller en orientation ne sont pas la même personne.
