### ISSUE TITLE
Les enseignants ne peuvent pas évaluer les apprentissages dans les SAés

### ISSUE THREAD

**Issue by GhisDUGAT** [avenirs-esr/GT-Test#28]

**Comment by giraudin** [comment]
Ce n'est pas un bug, c'est un choix. Les enseignants ne voulaient pas avoir à cliquer de partout dans les nombreuses saé qu'ils doivent évaluer quand nous avons crée KAPC+. Seul l'étudiant, le pair et le tuteur pro peuvent le faire, car eux ne le font qu'occasionnellement. 

Je ne suis pas contre l'option d'ajouter aussi l'enseignant "facultativement" mais à condition que ça ne génère pas de développements longs et de nouveaux bugs. Mon projet de vie devait être livré en mars, attention nous sommes très en retard.

**Comment by giraudin** [comment]
@Olivier-gerbe Regarder si on peut rajouter l'enseignant dans le menu ajouter les évaluation des niveaux des apprentissages (facile ?)

**Comment by AdrienPrugnaud** [comment]
Testé, l'évaluation par les enseignants apparaît bien dans le menu. A confirmer par @giraudin @GhisDUGAT

**Comment by giraudin** [comment]
@marusmb tu peux tester et répondre à Adrien ?

**Comment by marusmb** [comment]
C'est bon

**Comment by isabelle-roy** [comment]
Cela a introduit un bug, que j'ai corrigé cette fin de semaine. Il faut que vous arrêtiez de nous demander des améliorations sinon vous ne pourrez jamais livrer. On était supposé faire uniquement de la correction de bugs.
