### ISSUE TITLE
La liste des niveaux de mobilisation des apprentissages : carré gris correspond à non évalué MAIS dans la liste est noté non MOBILISE

### ISSUE THREAD

**Issue by GhisDUGAT** [avenirs-esr/GT-Test#29]

**Comment by olivier-gerbe** [comment]
Impossible de comprendre le problème. Il faut plus d'infos: description +printscreen

**Comment by Isamath** [comment]
@olivier-gerbe 
![Capture1](https://github.com/avenirs-esr/GT-Test/assets/105660222/635e9116-c664-41eb-96a5-349a3a72f987)
![Capture2](https://github.com/avenirs-esr/GT-Test/assets/105660222/8a6e24eb-ed4d-4bee-bb98-06b61cf25db7)
![Capture3](https://github.com/avenirs-esr/GT-Test/assets/105660222/8b623c16-c6a4-407d-bd02-57c33466dc8f)

**Comment by AdrienPrugnaud** [comment]
Je confirme le problème est toujours présent @olivier-gerbe

**Comment by isabelle-roy** [comment]
Je ne suis pas capable de reproduire le problème sur notre serveur. Je peux vous rencontrer si vous voulez me montrer sur votre serveur. 

![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/c8b00b3d-697a-4bf9-bcc8-3e16898ff209)

![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/93ea272b-ff36-42fb-b6fa-6673449e7e4c)

![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/1edee5ca-1b54-4ae2-af7d-2376aba122bf)

**Comment by AdrienPrugnaud** [comment]
@isabelle-roy il y a plusieurs problèmes : 
- comme sur ta capture d'écran il n'y a pas de texte quand on sélectionne le carré gris (il devrait y avoir marqué "non évalué") : 

![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/db7c7738-5403-4f8e-b500-80bccc479da1)

- le carré gris est sélectionné par défaut quand l'apprentissage est ajouté (dans une action comme une SAé...) mais le texte n'est pas présent : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/872972ad-b4ef-4170-b298-f0a15fa6d50e)

+ sur mon installation il faut que je passe mon curseur pour voir le texte s'affiché : 
![XybIgDL](https://github.com/avenirs-esr/GT-Test/assets/97050678/a4f68d73-722a-4869-886b-74489f65976e)

**Comment by isabelle-roy** [comment]
Fait sur ePortfolium
Sera livré avec la prochaine version sur nextcloud

![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/0317bc1a-80b4-45de-bf06-0672fb496c86)

Et nouveau CSS

![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/d3545361-de2d-4e27-92df-6b9f31f4b8b9)

**Comment by AdrienPrugnaud** [comment]
@AdrienPrugnaud A tester

**Comment by AdrienPrugnaud** [comment]
@isabelle-roy on ne s'était pas dit que l'on retourner en arrière en marquant "non évalué", "bien mobilisé"... à la place de "Gris", "vert"... ? quand on passe le curseur sur le carré de couleur. Car là c'est l'inverse qui a été fait : 
@giraudin peux-tu confirmer stp ?
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/3ada62de-25ed-44f3-a502-72c63092a857)

**Comment by isabelle-roy** [comment]
C'était un autre issue et on a dit qu'il n'y a pas assez de place en largeur, ça dépasse dans l'autre colonne (sur un laptop). Éric a dit on laisse tomber.

**Comment by AdrienPrugnaud** [comment]
@GhisDUGAT @jgribonvald Il faudrait fermer l'issue

**Comment by AdrienPrugnaud** [comment]
A fermer @jgribonvald
