### ISSUE TITLE
L’enseignant ne voit pas les traces ajoutées

### ISSUE THREAD

**Issue by GhisDUGAT** [avenirs-esr/GT-Test#30]

**Comment by giraudin** [comment]
@GhisDUGAT 
Tu peux détailler ? Dans tous les types d'actions du module APC ou dans celui du projet de vie ?

**Comment by GhisDUGAT** [comment]
Lorsqu'une SAé est soumise par un étudiant en APC, ses traces ne peuvent pas être visualisées par l'enseignant
![Capture d’écran du 2024-03-04 08-54-20](https://github.com/avenirs-esr/GT-Test/assets/137498177/409eb80d-fa11-41d9-870b-f214dd7e338f)
![Capture d’écran du 2024-03-04 08-54-12](https://github.com/avenirs-esr/GT-Test/assets/137498177/2a933e9d-6b61-4e5a-8b4b-c651ae064e21)

**Comment by giraudin** [comment]
Bizarre sur l'installation USMB je les vois en tant qu'enseignant et pour les 2 types de sae avec évaluateurs imposés par l'enseignant et ceux choisis par l'étudiant

**Comment by jgribonvald** [comment]
à vérifier si ça ne vient pas d'une évaluation supprimée

**Comment by Isamath** [comment]
cf issue #18

**Comment by AdrienPrugnaud** [comment]
@olivier-gerbe @Isamath @giraudin J'ai le même problème avec la dernière version : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/539edb4d-7701-4285-987d-63d7986c9bca)

**Comment by giraudin** [comment]
@marusmb tu peux tester ?

**Comment by marusmb** [comment]
Problème toujours présent pour les quatre types de traces.
