### ISSUE TITLE
Modifications / améliorations

### ISSUE THREAD

**Issue by GhisDUGAT** [avenirs-esr/GT-Test#31]
FAUTES D’ORTHOGRAPHE ou de FORMULATION
    • Formulaire APC Association enseignant-formation : « Les enseignants ne sont pas crééS pour une formation en particulier »
    • Dans les Saés / apprentissages/évaluations Réflexion sur ma LA mobilisation de cet apprentissage﻿

MODIFICATIONS / AMELIORATIONS
    • Modifier « Feedback de mon enseignant » par « Demande de feedback » ou « Demander un feedback »
    • Il y a beaucoup d’endroits dans le portfolio à mon avis ou il faudrait opter pour le mode « Edition en place » qui permet d’éviter des clics : 
- Dans feedback pour la question
- dans l’auto évaluation des apprentissages
- dans l’auto-évaluation finale, dans les commentaires de l’auto-évaluation
- pour les réponses et commentaires des enseignants, si on peut leur éviter un clic à chaque fois !
    • Il faut enlever la flèche de Tri (dans PPP) sur l’association des évaluateurs, elle ne sert à rien (et les étudiants croient qu’elle permet d’envoyer une demande), et sur l’association des évaluateurs dans les saés
    • Dans la synthèse Inverser NOM prénom par Prénom NOM
    • Dans la page liste des SAés des étudiants, ce n’est pas affiché qd ils ont fait une demande d’évaluation (juste non évaluée ou évaluée)

**Comment by AdrienPrugnaud** [comment]
@giraudin Est-ce que cela te convient ?

**Comment by isabelle-roy** [comment]
Amélioration, pas un bug

**Comment by isabelle-roy** [comment]
- J'ai corrigé la faute d'orthographe sur la page d'accueil du portfolio Formulaires APC et le texte dans l'auto-évaluation des AC des SAés.
- J'ai retiré le droit d'ordonner les enseignants et les conseillers internes.
- J'inversé nom et prénom dans la base de cv.

Pour les demandes de feedback au bas de chacune des pages du portfolio PP, j'ai changé _Ajouter une question_ par _Demander un feedback_ puis le bouton _Envoyer_ par _Envoyer la question_. Il faut faire ça sur 3 onglets x 6 pages, on ne va pas s'amuser à changer ça plusieurs fois. Quelqu'un va devoir vérifier que je n'ai pas introduit d'erreur nulle part. Je n'ai pas changé le libellé de la section parce que c'est le même dans le portfolio APC.

Pour ce qui est de mettre les champs édition en place cela changerait complètement le design d'Éric. À voir avec lui, je ferai ce qu'il me dira. Pour les étudiants, ePortfolium ne recommande généralement pas l'utilisation de formulaires pour un travail réflexif. Par contre pour les enseignants je comprends l'enjeu vu le nombre d'étudiants. J'ai fait des tests d'édition en place pour l'enseignant et dans le pop-up à partir de son portfolio ce n'est pas bon tel quel. Si on allait dans cette direction il faudrait faire du débuggage dans l'affichage qu'on obtiens quand on clique sur les jumelles. Je joins des printscreens.

![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/c9114416-dfbb-446a-854f-860426a7811a)
![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/5bfc855d-542f-4d12-8035-70b5db9c0a70) 
![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/687efd68-0e3e-4a50-99ba-c262cb35b7f0)

**Comment by giraudin** [comment]
Nous sommes trop à la bourre, donc si il faut faire de déboggage on laisse tomber l'édition en place
