### ISSUE TITLE
Création Portfolio projet de vie via fichier CSV le portfolio APC n'est plus visible

### ISSUE THREAD

**Issue by marusmb** [avenirs-esr/GT-Test#32]
Dans le fichier CSV, que l'on mette dans la cellule D2 "@oui" ou "@non", le portfolio APC n'est plus visible. 
De plus je n'ai pas trouvé la solution pour rendre à nouveau visible le portfolio APC

**Comment by isabelle-roy** [comment]
Bonjour M. Marquette, voici une nouvelle version du fichier csv. Je le remplace dans votre portfolio Formulaires (sur votre serveur). Isabelle
[modèle csv créer étudiants projet de vie.csv](https://github.com/avenirs-esr/GT-Test/files/14574037/modele.csv.creer.etudiants.projet.de.vie.csv)

**Comment by isabelle-roy** [comment]
J'ai corrigé le fichier CSV.
Nouveau module `9A. Projet de vie` qui corrige les issues #32, #33 et #34 :
[9A Projet de vie.zip](https://github.com/avenirs-esr/GT-Test/files/14575121/9A.Projet.de.vie.zip)

**Comment by marusmb** [comment]
Problème corrigé, modification appliquée sur la plateforme de tests.
