### ISSUE TITLE
Suppression Conseiller via fichier CSV ne supprime que le premier

### ISSUE THREAD

**Issue by marusmb** [avenirs-esr/GT-Test#33]
La suppression des conseillers par fichiers CSV ne supprime que le premier de la liste. En supprimant la ligne contenant le conseiller supprimer et en recommençant la suppression avec le fichier csv uniquement le nouveau conseiller se trouvant en première ligne est supprimé.

**Comment by isabelle-roy** [comment]
J'ai corrigé le script de batch et le fichier CSV.
Nouveau module `9A. Projet de vie` qui corrige les issues #32, #33 et #34 :
[9A Projet de vie.zip](https://github.com/avenirs-esr/GT-Test/files/14575121/9A.Projet.de.vie.zip)

**Comment by marusmb** [comment]
Problème corrigé, modification appliquée sur la plateforme de tests.

**Comment by marusmb** [comment]
Problème présent sur la dernière version

**Comment by AdrienPrugnaud** [comment]
A confirmer par @marusmb 
J'ai testé et cela fonctionne au GIP

**Comment by marusmb** [comment]
C'est OK pour moi
