### ISSUE TITLE
Suppression Portfolio projet de vie Etudiant via fichier CSV ne supprime que le premier

### ISSUE THREAD

**Issue by marusmb** [avenirs-esr/GT-Test#34]
La suppression des portfolio projet de vie étudiant par fichiers CSV ne supprime que le premier de la liste. En supprimant la ligne contenant le portfolio supprimé et en recommençant la suppression avec le fichier csv uniquement la première ligne est supprimé.

**Comment by isabelle-roy** [comment]
J'ai corrigé le script de batch et le fichier CSV.
Nouveau module `9A. Projet de vie` qui corrige les issues #32, #33 et #34 :
[9A Projet de vie.zip](https://github.com/avenirs-esr/GT-Test/files/14575121/9A.Projet.de.vie.zip)

**Comment by marusmb** [comment]
Problème corrigé, modification appliquée sur la plateforme de tests.
