### ISSUE TITLE
La suppression compte enseignant.

### ISSUE THREAD

**Issue by marusmb** [avenirs-esr/GT-Test#35]
Si l'on supprime un enseignant par formulaire ou fichier csv, il n'est pas supprimé des formations sur lesquelles il était associé.

**Comment by isabelle-roy** [comment]
Bonjour Michel,
Lors du développement de KAPC 1.3 le RECIA nous avait demandé de séparer la création/suppression de compte & portfolio enseignant de l'association/dissociation avec une ou des formations (parce qu'ils ont des enseignants qui travaillent dans plusieurs formations).
La marche à suivre pour un enseignant est la suivante :

- Créer le compte et portfolio enseignant
- Associer l'enseignant à une formation (*répéter autant de fois que nécessaire)
- Dissocier l'enseignant d'une formation (*répéter autant de fois que nécessaire)
- Supprimer le compte et le portfolio enseignant.

Tout ceci se fait dans le module APC (portfolio Formulaires APC pour formulaires ou modèles de fichiers CSV).

**Comment by AdrienPrugnaud** [comment]
@jgribonvald @marusmb A Clôturer si c'est bon pour vous

**Comment by marusmb** [comment]
C'est bon pour moi
