### ISSUE TITLE
Coquille dans page d'accueil Portfolio APC rubirque "Besoin d'un coup de main"

### ISSUE THREAD

**Issue by marusmb** [avenirs-esr/GT-Test#38]
Il manque un mot dans la partie de la phrase "vous aider dans la construction de votre personnel de réussite étudiante"

**Comment by olivier-gerbe** [comment]
@giraudin 
ou vous aider dans la construction de votre cheminement de réussite étudiante et professionnelle.
Correct ?

**Comment by AdrienPrugnaud** [comment]
@marusmb est-ce que la modification te convient : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/41ad6f39-599f-41fd-ac3a-b20adff60a70)
Si oui, issue à clôturer

**Comment by marusmb** [comment]
OK
