### ISSUE TITLE
Portfolio Projet pro, Saisie date propose le choix par jour et ne retient que l'année

### ISSUE THREAD

**Issue by marusmb** [avenirs-esr/GT-Test#39]
Dans la partie Faire mon bilan/Mes expériences: le choix date de fin propose calendrier complet mais mémorise que l'année. En revanche pour la date de début il y a bien que l'année qui est proposée.

**Comment by marusmb** [comment]
Problème présent sur les 3 onglet "Expérience professionnelles", "Stages et alternances" et "Expériences personelles"

**Comment by olivier-gerbe** [comment]
Il faut teste la version mise sur Nextcloud la semaine derniére.

**Comment by olivier-gerbe** [comment]
@giraudin 
Vous voulez année seulement ou mois / année ou jour/mois/année

**Comment by AdrienPrugnaud** [comment]
@giraudin quel choix serait le mieux selon toi ?

**Comment by AdrienPrugnaud** [comment]
Je penses que @marusmb parle des choix retenus par défaut comme ici avec mon navigateur : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/6cc83f2f-4c87-4958-b060-381ee26c49ec)
Eportfolium n'a pas de contrôle sur le widget calendrier pour faire le choix des dates donc cela peut venir de notre navigateur/historique... 

Car quand on clique ici sur les dates comme cela  : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/49b8bdde-6181-4271-b84d-baa58ca79df2)

On a bien le choix de l'année seulement : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/78a4dd03-2fc4-42e7-b096-4e842531513e)

**Comment by marusmb** [comment]
C'était le menu en vert qui proposait le choix de la date complète jour, mois et année pour conserver uniquement l'année. C'est corrigé.

**Comment by AdrienPrugnaud** [comment]
Top merci
