### ISSUE TITLE
Où trouver les référentiels de compétences

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#4]
Les référentiels de compétences en zip (et à jours au niveau de la version par exemple 1.3.5) ne sont plus téléchargeables dans les portfolios "QUICKSTART" et "Formulaires". Il faudrait peut-être les remettre pour que cela soit plus pratique lors du dérouler de ceux-ci

**Comment by jgribonvald** [comment]
En fait je ne suis vraiment pas fan de ce système, je préfère qu'on indique à l'utilisateur où trouver le zip que plutôt de figer une URL qui ne durera pas dans le temps.

Il faut savoir que les référentiels sont fournis dans le karuta-deployer, qu'ils dépendent de la version du deployer, et donc des différents applicatifs de karuta. Et seules des versions ont des URL fixes, sauf qu'on ne versionne qu'après coup.
