### ISSUE TITLE
Nouveau développement : classer par niveau dans le tableau de bord qui fait la synthèse des actions et des apprentissages

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#41]
Bonjour à tous,
Nous avons un nouveau développement à vous soumettre :
Dans le tableau de bord d'une compétence dans la rubrique "Mes bilans par compétence" les actions et apprentissages présents dans la "Synthèse des apprentissages critiques de cette compétence développés dans vos actions" ne sont pas du tout classé. Ainsi les étudiants et enseignants se perdent, surtout en 3ème année quand il y a beaucoup d'actions dans ce tableau : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/121c928e-b9c4-461e-bf6e-41ca47c4df4d)
Serait-il possible de modifier ce tableau de bord pour les classer par niveau les actions et apprentissages ?
Ex : toutes les actions de niveau 1 en premier, puis le niveau 2 puis le 3.

Ou alors comme pour les reculs réflexifs, un classement par année (du coup ce serait un classement par niveau : bilan actions  niveau 1, bilan niveau 2..) : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/e84c7674-cd69-4085-8a40-d12883f8ce93)

**Comment by giraudin** [comment]
Ce qui pourrait donner ça :

![image](https://github.com/avenirs-esr/GT-Test/assets/7628798/689b5335-b558-48e1-9673-b27365ee507b)

**Comment by olivier-gerbe** [comment]
@giraudin 
Où est l'exemple ci-dessus pour que l'on comprenne bien ?

**Comment by AdrienPrugnaud** [comment]
@olivier-gerbe @isabelle-roy l'exemple de ce que l'on souhaiterait est l'image d'Eric : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/7ffaaee5-2c6b-43aa-8998-2c916c823bd5)

**Comment by olivier-gerbe** [comment]
Je veux dire le portfolio lui-même pour pouvoir tester le rapport.

**Comment by AdrienPrugnaud** [comment]
@marusmb serait-il possible de transmettre un accès admin à @olivier-gerbe sur votre serveur svp (car nous n'avons pas la 1.4 d'installée au GIP)

**Comment by marusmb** [comment]
@AdrienPrugnaud  c'est fait, je lui ai envoyé id et mdp

**Comment by AdrienPrugnaud** [comment]
super merci !

**Comment by AdrienPrugnaud** [comment]
Fonctionne correctement, à valider avec Eric si on part sur des niveaux à dépliés contrairement à ce qu'il y a actuellement. Ce qui donnerait : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/c92ed5cf-ac19-4818-97b5-9759c995c33a)

Il faudrait aussi changer le titre de la section en : "Synthèse des apprentissages critiques (regroupés par niveaux) de cette compétence développés dans vos actions"

**Comment by AdrienPrugnaud** [comment]
Si possible si cela ne prend pas trop de temps, ce serait d'harmoniser la taille des polices pour qu'elles correspondent à la même chose que celles du recul réflexifs (agrandir "Niveau 1...." au même niveau que "Bilan réflexif" à droite et réduire un peu la taille de la police de " Compétence 1 niveau 1").
Vraiment si cela ne prend pas trop de temps car c'est du détail : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/3ee2f251-525f-496f-8b64-7b75f787222b)

**Comment by olivier-gerbe** [comment]
@isabelle-roy @giraudin @AdrienPrugnaud 
Fait. J'ai déposé une nouvelle version sur Nextcloud

**Comment by AdrienPrugnaud** [comment]
Merci @olivier-gerbe @isabelle-roy @giraudin 
Testé, il reste juste à paramétrer le fait les sections des niveaux de compétence soient refermées par défaut + inverser la taille de la police pour que le titre de la section soit plus grand que celui des actions qui sont reprises (peut-être s'aligner avec la taille des sections des reculs réflexifs par années) :
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/dc0e96b4-df0f-4b4a-951d-1217eefd7293)

**Comment by olivier-gerbe** [comment]
@olivier-gerbe @isabelle-roy @giraudin
Voici un exemple sur KAPC14
C'est fermé par défaut.

<img width="580" alt="Capture d’écran, le 2024-04-29 à 10 18 43" src="https://github.com/avenirs-esr/GT-Test/assets/8060484/085718fd-c15f-442a-9ba3-d9966e9b2b80">
<img width="576" alt="Capture d’écran, le 2024-04-29 à 10 18 52" src="https://github.com/avenirs-esr/GT-Test/assets/8060484/58da739b-cbf6-4c7c-8ff9-53f2a8ad6d08">

**Comment by AdrienPrugnaud** [comment]
@olivier-gerbe @isabelle-roy @giraudin C'est bon pour moi avec la capture d'écran 1 "fermé par défaut" et avec la nouvelle police c'est plus lisible

**Comment by AdrienPrugnaud** [comment]
@olivier-gerbe Récapitulatif de ce qu'il reste à faire.
1- Uniformiser l'ordre des sections de niveau (niveau 1, 2 et 3) aussi bien pour les nouveaux que pour les portfolios déjà créés car pour l'instant cela donne par exemple le niveau 3, 2 et 1 (pour les anciens portfolios) : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/8dcad8e4-0bac-4b44-8668-10d01a7d9d85)
de plus si l'étudiant rajoute le niveau 1 après l'ajout des niveaux 2 et 3 il ne se place par chronologiquement : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/2c517b14-7a02-4d88-b24f-311a5258b587)
2- D'avoir par défaut pour les nouveaux et anciens portfolios les sections de niveau repliées comme ceci : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/1f938901-3956-479d-bc76-f03fb33eaf01)
3- De remettre la phrase : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/1eef7cba-2368-4053-9250-8f6a20db778e)

**Comment by olivier-gerbe** [comment]
L'ordre est celui qui se trouve dans la page compétences de l'étudiant si il a ajouté niveau 3 avant niveau 1 alors niveau 3 apparait avant niveau dans la synthèse. Si l'étudiant les veut dans l'ordre, il lui suffit de les supprimer et de les ajouter dans l'ordre dans sa page compétence.

**Comment by isabelle-roy** [comment]
Note additionnelle : je vous dis tout de suite au cas où vous penseriez à me demander une flèche pour ordonner les niveaux dans la page Formation de l'étudiant : ce morceau est importé directement des référentiels de compétences, alors pour ajouter la flèche il faudrait modifier par batch les métadonnées de tous les niveaux dans tous les référentiels de compétences puis que toutes les universités remplacent tous leurs référentiels de compétences ! Et si ils ont leurs propres référentiels de compétences il faudrait qu'ils exécutent eux-même le batch de modification des métadonnées.

**Comment by AdrienPrugnaud** [comment]
Merci pour ces informations, c'est bon pour moi
