### ISSUE TITLE
Projet de vie - faire mon bilan dans les possibilités proposées pour "Afficher dans Ma synthèse" proposer uniquement Oui ou Non

### ISSUE THREAD

**Issue by marusmb** [avenirs-esr/GT-Test#42]
Les rubriques "Afficher dans Ma synthèse" dans la partie "Faire mon bilan" propose 3 choix, seule 2 sont possible.

**Comment by giraudin** [comment]
@olivier-gerbe test

**Comment by giraudin** [comment]
@isabelle-roy test

**Comment by olivier-gerbe** [comment]
C'est le fonctionnement de base de Karuta, le premier choix permet de faire un reset de l'élément. Il est vrai que dans ce cas ce n'est pas utile. On pourrait le cacher par CSS si désiré. De même pour le statut.
QUESTION : Est-ce qu'on les cache ?

**Comment by AdrienPrugnaud** [comment]
@giraudin : 
C'est le fonctionnement de base de Karuta, le premier choix permet de faire un reset de l'élément. Il est vrai que dans ce cas ce n'est pas utile. On pourrait le cacher par CSS si désiré. De même pour le statut.
**QUESTION : Est-ce qu'on les cache ?**
Pour moi ce n'est pas prioritaire

**Comment by isabelle-roy** [comment]
Amélioration, pas un bug

**Comment by marusmb** [comment]
@giraudin @AdrienPrugnaud 
Il n'y a aucune différence entre le choix et le non, je pense également que ce n'est pas gênant de le laisser.

**Comment by isabelle-roy** [comment]
J'ai regardé mais je n'ai pas trouvé de façon facile et rapide de cacher juste ça. Je pense qu'on laisse faire pour cette version sinon on ne livrera jamais...
