### ISSUE TITLE
Projet de vie - Après suppression d'un conseiller il apparait toujours dans "Répertoire de conseillers Projet de vie"

### ISSUE THREAD

**Issue by marusmb** [avenirs-esr/GT-Test#43]
Quand on supprime un conseiller par batch ou par formulaire, le compte est bien inactif, en revanche, il reste présent dans le "Répertoire de conseillers Projet de vie".
Si on le crée de nouveau il apparait 2 fois dans le répertoire.
![liste conseillers](https://github.com/avenirs-esr/GT-Test/assets/160909485/0066941f-6a1e-4488-bfea-7ec59947a22c)

**Comment by marusmb** [comment]
@isabelle-roy 
@olivier-gerbe

**Comment by olivier-gerbe** [comment]
Je viens de tester l'ajout et suppression de conseiller sur le serveur de test USMB avec le compte d'Isabelle et tout est correct.

**Comment by marusmb** [comment]
Lorsque qu'un compte étudiant demande un feedback la liste des conseillers qui lui est présentée correspond aux comptes conseiller présent dans le "Répertoire de conseillers Projet de vie".
Comme dans celle-ci il y a encore les conseillers dont le compte a été supprimer, il est possible de demander un feedback à un conseiller dont le compte n'existe plus. Je viens d'expliquer le problème à Isabelle. @olivier-gerbe

**Comment by isabelle-roy** [comment]
Correction à faire dans Karuta. À suivre.
@olivier-gerbe C'est le problème des fonctions .resourceCodeContains({'value':'###XYZ###'}) vs .resourceCodeContains('###XYZ###').

**Comment by AdrienPrugnaud** [comment]
@olivier-gerbe  @isabelle-roy correction apportée ?

**Comment by isabelle-roy** [comment]
Il n'y a rien de modifié dans le batch
Je ne sais pas si Olivier a modifié Karuta ni si je dois modifier le batch
Il est absent actuellement
Je ne peux pas me prononcer sans le consulter

**Comment by marusmb** [comment]
C'est bon pour moi
