### ISSUE TITLE
Les batchs de suppression suppriment le compte et le portfolio

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#44]
Quand on utilise le batch de suppression des conseillers d'orientation cela supprime aussi le compte (on ne peut plus se connecter car le batch supprime le login).
Ainsi si un enseignant et aussi bien évaluateur que conseiller et que l'on passe un des batchs de suppression, il n'aura plus accès à son compte.
Il faudrait que le batch supprime seulement la partie conseiller ou seulement la partie évaluateur pour les batchs de suppressions côter évaluateurs.
@olivier-gerbe 

La seule solution que j'ai trouvé c'est de repasser le batch de création évaluateur et associer évaluateur mais cela devient vite compliqué si on essaie d'automatiser la gestion des comptes.

**Comment by isabelle-roy** [comment]
Est-ce que c'est un cas réel ? Est-ce qu'il y a vraiment des enseignants KAPC qui sont conseillers PP ? Quand on en avait discuté avec Éric l'hiver dernier il nous avait dit que non, que ce n'étaient pas les mêmes personnes...
Si je change maintenant il y aura 4 nouveaux batchs et 4 nouveaux CSV. Ça implique toujours une possiblité d'introduire des bugs. Il faudra retester.
Dites-moi si vous voulez que je procède quand même.
@giraudin

**Comment by isabelle-roy** [comment]
Pour la 1.4 on considère que un enseignant et un conseiller en orientation ne sont pas la même personne.
