### ISSUE TITLE
Batch suppression portfolio APC supprime l'accès au compte étudiant

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#45]
Concernant batchs de suppressions étudiants :
Si on passe le batch suppression de la partie projet de vie, seule la partie projet de vie est supprimée. (c'est bon)

Mais si on passe le batch suppression étudiant KAPC+ "modèle csv supprimer étudiants v1-3" le compte est aussi supprimé et l'étudiant n'a plus accès à son portfolio projet de vie.

@olivier-gerbe

**Comment by isabelle-roy** [comment]
Je vous envoie un rappel du mode de fonctionnement de KAPC 1.4 sur lequel nous nous sommes entendus :

1. Créer les comptes et portfolios enseignants dans le module Compétences
2. Créer les comptes et portfolios en compétences des étudiants dans le module Compétences
3. Créer les comptes conseillers PP dans le module PP 
4. Créer portfolios étudiants PP dans le module PP
5. Supprimer les portfolios étudiants PP dans le module PP
6. Supprimer les comptes conseillers PP dans le module PP
7. Supprimer les comptes et portfolios en compétences étudiants dans le module Compétences
8. Supprimer les comptes et portfolios enseignants dans le module Compétences.

Il est important de respecter l'ordre des opérations : 
Créations : module Compétences -> module PP 
Suppressions : module PP -> module Compétences

**Comment by giraudin** [comment]
Bonsoir,Ce comportement vient sûrement du fait que nous souhaitions que le projet de vie ne puisse être ajouté que si le portfolio de compétence (Apc) existait déjà.Le 28 mai 2024 à 18:14, Isabelle Roy ***@***.***> a écrit :﻿
Je vous envoie un rappel du mode de fonctionnement de KAPC 1.4 sur lequel nous nous sommes entendus :

Créer les comptes et portfolios enseignants dans le module Compétences
Créer les comptes et portfolios en compétences des étudiants dans le module Compétences
Créer les comptes conseillers PP dans le module PP
Créer portfolios étudiants PP dans le module PP
Supprimer les portfolios étudiants PP dans le module PP
Supprimer les comptes conseillers PP dans le module PP
Supprimer les comptes et portfolios en compétences étudiants dans le module Compétences
Supprimer les comptes et portfolios enseignants dans le module Compétences.

Il est important de respecter l'ordre des opérations :
Créations : module Compétences -> module PP
Suppressions : module PP -> module Compétences

**Comment by AdrienPrugnaud** [comment]
Bonjour à tous,

Merci pour vos retours.
Pendant un temps il avait été annoncé que les deux portfolios pouvaient fonctionner séparément c'est pour ça que j'avais fait ces tests.

Bonne journée,
Cordialement,
Adrien

Le Mardi 28 Mai 2024 21:38 CEST, Eric Giraudin ***@***.***> a écrit:
 
 Bonsoir,Ce comportement vient sûrement du fait que nous souhaitions que le projet de vie ne puisse être ajouté que si le portfolio de compétence (Apc) existait déjà.Le 28 mai 2024 à 18:14, Isabelle Roy ***@***.***> a écrit :﻿
Je vous envoie un rappel du mode de fonctionnement de KAPC 1.4 sur lequel nous nous sommes entendus :

Créer les comptes et portfolios enseignants dans le module Compétences
Créer les comptes et portfolios en compétences des étudiants dans le module Compétences
Créer les comptes conseillers PP dans le module PP
Créer portfolios étudiants PP dans le module PP
Supprimer les portfolios étudiants PP dans le module PP
Supprimer les comptes conseillers PP dans le module PP
Supprimer les comptes et portfolios en compétences étudiants dans le module Compétences
Supprimer les comptes et portfolios enseignants dans le module Compétences.

Il est important de respecter l'ordre des opérations :
Créations : module Compétences -> module PP
Suppressions : module PP -> module Compétences

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***> 


--

 Adrien PRUGNAUD / Chargé de mission ePortfolio
Port. +33 (0)6 49 17 61 ***@***.***

GIP Recia · Ressources numériques publiques en Centre-Val de Loire
Antenne de Touraine · 4-6, boulevard de Chinon · 37510 BALLAN-MIRÉ
Tél. 02 38 42 79 60
www.recia.fr ·

**Comment by isabelle-roy** [comment]
Bonjour Adrien, 

Les deux portfolios peuvent effectivement fonctionner séparément. 
Mais il a été décidé que les traces sont conservées dans le portfolio APC, donc celui-ci doit toujours exister. Ce qui se passe si une institution désire utiliser uniquement le module PP, c'est qu'au moment de créer le portfolio étudiant PP l'admin coche Portfolio APC Non Visible. Nous cachons alors à l'étudiant son portfolio APC, qui lui sert uniquement de répertoire de traces. 
Mais il faut en tout temps resperter l'ordre des modules : 
Créations : module APC -> module PP
Suppressions : module PP -> module APC

Cordialement,
Isabelle

**Comment by isabelle-roy** [comment]
Bonjour Adrien,

Les deux portfolios peuvent effectivement fonctionner séparément.
Mais il a été décidé que les traces sont conservées dans le portfolio APC, donc celui-ci doit toujours exister. Ce qui se passe si une institution désire utiliser uniquement le module PP, c'est qu'au moment de créer le portfolio étudiant PP l'admin coche Portfolio APC Non Visible. Nous cachons alors à l'étudiant son portfolio APC, qui lui sert uniquement de répertoire de traces.
Mais il faut en tout temps resperter l'ordre des modules :
Créations : module APC -> module PP
Suppressions : module PP -> module APC

Cordialement,
Isabelle

**Comment by isabelle-roy** [comment]
ps. Petit rappel : la personne en charge de distribuer kapc 1.4 à la communauté devra inclure les instructions d'utilisation. Olivier m'avait dit que ce ne serait pas moi, c'est pour ça que je vous avais envoyé les instructions dans un courriel de livraison le 6 février. À ne pas oublier !! :-)
