### ISSUE TITLE
Evaluation des enseignants concernant les apprentissages critiques qui n'apparaissent pas dans le bilan de compétence

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#46]
En rapport ave la #28 
L'évaluation des enseignants pour les apprentissages critiques n'apparait pas dans le bilan de compétence de l'étudiant : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/2c4753a1-378c-4830-84b5-c572d44e9c66)

Voici ce que l'on voit dans le bilan : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/42fdfea4-b2af-4ddd-adeb-2b3e7622e709)

@olivier-gerbe

**Comment by isabelle-roy** [comment]
Allo Adrien,

Je ne comprends pas comment tu es arrivé au premier printscreen : les enseignants ne se prononcent pas sur les apprentissages critiques, ça leur ferait trop de travail... il font une évaluation globale de la page... 
À moins que vous ayez ajouté l'évaluation par l'enseignant après que j'ai livré kapc 1.4 en février ?? Dans la version que j'ai livré en février il n'y a pas d'évaluation des AC par l'enseignant.
@giraudin Est-ce que tu peux m'expliquer ce qui se passe ici ? Je suis vraiment prise au dépourvu.

Isabelle

**Comment by isabelle-roy** [comment]
![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/ac2b85fe-051c-4c99-a339-1842dc3a048e)
L'évaluation par l'enseignant n'est pas un choix...

**Comment by AdrienPrugnaud** [comment]
@isabelle-roy Est-ce que tu as la dernière version ? Car j'ai bien ce choix et j'ai pris les versions déposées sur nextcloud

**Comment by isabelle-roy** [comment]
@AdrienPrugnaud Je ne sais pas, j'ai la version que je t'ai livrée en février et sur laquelle je travaille quand vous me soumettez des bugs. Je vous ai déposé une nouvelle version le 28 avril. Éric m'a toujours dit que les enseignants ne voulaient pas avoir ce niveau de granularité, que ça leur ferait trop de travail. Mais peut-être que quelqu'un a demandé ça à Olivier et qu'il l'a fait sans m'en parler. Il faudrait qu'Éric se prononce là-dessus. @giraudin 

ps. Si tu veux me rencontrer en visio et qu'on regarde ensemble ça peut peut-être accélerer le processus...

**Comment by isabelle-roy** [comment]
Fait sur ePortfolium
Sera livré avec la prochaine version sur nextcloud

**Comment by AdrienPrugnaud** [comment]
@AdrienPrugnaud A tester

**Comment by AdrienPrugnaud** [comment]
Fait : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/2e57213f-1ffe-4713-a834-d79aa5c00e98)
