### ISSUE TITLE
Bouton "envoyer" concernant l'évaluation par les enseignants des apprentissages critiques

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#47]
En rapport avec la #28 
A quoi sert le bouton "envoyer", est-il nécessaire ?
Car même sans cliquer sur "envoyer" dessus l'étudiant voit bien l'évaluation de l'enseignant.
Voici la vue par l'enseignant qui n'a pas cliquer sur "Envoyer" : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/889a1543-8dd3-4fd8-8bed-09be86baefb4)

voici ce que voit l'étudiant : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/f5927507-5018-4312-8f09-3f912671765f)

@olivier-gerbe

**Comment by isabelle-roy** [comment]
"Envoyer" est le texte qui nous a été demandé pour le bouton Soumettre.
Après soumission l'utilisateur ne peut plus modifier son choix.
Tous les éléments qui sont accessibles via un partage par courriel doivent être soumis pour des raisons de sécurité : au cas où quelqu'un qui n'est pas le destinataire voulu aurait accès au courriel avec l'hyperlien.
On peut mettre n'importe quel texte sur le bouton Soumettre.

**Comment by isabelle-roy** [comment]
L'enseignant ne reçoit pas de courriel. Je vais retirer le bouton Envoyer.

**Comment by isabelle-roy** [comment]
Fait sur le serveur ePortfolium.
Sera livré avec la prochaine version sur nextcloud.

![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/0be51c49-25f9-4d4e-97be-d3467e17cfce)

**Comment by AdrienPrugnaud** [comment]
@AdrienPrugnaud à tester

**Comment by AdrienPrugnaud** [comment]
Fait : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/a6f8a0ae-77df-40b3-9b49-b0a87abeb6c6)
