### ISSUE TITLE
Rajouter plusieurs fois la même trajectoire dans "Bâtir mon projet"

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#48]
Dans le portfolio" Mon projet de vie" puis "Bâtir mon projet" après avoir rajouter une trajectoire possible, on peut la rajouter x fois.
Est-ce qu'il serait possible de ne pas pouvoir rajouter une trajectoire si elle a déjà été rajoutée ?

https://github.com/avenirs-esr/GT-Test/assets/97050678/3eade36d-d71d-4e0d-b1c5-0b0984a2f259

Après ce n'est pas forcément grave/urgent ? @giraudin 
@olivier-gerbe

**Comment by isabelle-roy** [comment]
Allo Adrien,

Malheureusement dans ce cas-ci on n'est pas capables de faire autrement avec Karuta.
Version industrielle ?

Cordialement,
Isabelle

**Comment by giraudin** [comment]
et un étudiant peut hésiter entre plus trajectoire donc comportement normal.

**Comment by AdrienPrugnaud** [comment]
Ok merci pour cette explication
