### ISSUE TITLE
Changement de nom de "futur possible" dans "Explorer mon futur" qui n'est pas repris dans "Bâtir mon projet"

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#49]
Si je change le libellé d'un futur possible dans "Explorer mon futur" et que j'ai déjà ajouté ce futur possible dans "Bâtir mon projet", le changement de nom n'est pas pris en compte dans "Bâtir mon projet" : 

https://github.com/avenirs-esr/GT-Test/assets/97050678/cccc24aa-3e6f-4a3f-8118-45076051a76e

@giraudin C'est peut-être du détail mais je préfère le préciser voir ce que l'on fait
@olivier-gerbe

**Comment by giraudin** [comment]
C'est un bug. Il faudrait le corriger.

**Comment by olivier-gerbe** [comment]
C'est une copie qui est ajouter dans Batir mon projet. Donc le fait de modifier d'un coté ne modifie pas dans l'autre. L'étudiant peut modifier le libellé dans Batir mon projet et/ou Explorer mon futur indépendamment l'un de l'autre.

**Comment by isabelle-roy** [comment]
Malheureusement on n'est pas capables de faire ça avec Karuta.
Version industrielle ?

**Comment by AdrienPrugnaud** [comment]
Ok pas possible dans cette version
