### ISSUE TITLE
Bug rencontré au bout d'un certain temps d'inactivité - portfolio étudiant

### ISSUE THREAD

**Issue by MattLUnLille** [avenirs-esr/GT-Test#5]
Bonjour,

Je viens de rencontrer un bug d'affichage lié à une inactivité pendant plusieurs minutes : 
après être revenu sur ma session ouverte de karuta.recia.dev via le compte étudiant, voyant que les informations concernant "Mes bilans par compétence" -> "Compétences personnalisées" ->"Libellé de la compétence personnalisée (à modifier)" ne se chargeaient pas du tout, j'ai cliqué sur le bouton "Recharger" - celui à droite du bouton "éditer" - situé en haut à droite de la page du eportfolio.
Et là, le message d'erreur suivant "Attention [...]" (cf. pj) apparaît : 
![Capture d’écran 2023-07-17 110445](https://github.com/avenirs-esr/GT-Test/assets/139477155/246b2aad-f8b3-497a-a804-9a3442552dff)
J'ai voulu ensuite recharger à nouveau cette page et/ou aller sur la page d'accueil de mon eportfolio étudiant : ce message d'erreur ne disparaît pas et m'empêche de continuer à interagir sur les différentes pages du eportfolio.

**Comment by jgribonvald** [comment]
@olivier-gerbe pour avis s'il te plait. Merci
test de la version 1.3.5

**Comment by olivier-gerbe** [comment]
Oui, C'est dû à la durée de session du Tomcat qui doit être de 30mn, la valeur par défaut. Nous conseillons de l'augmenter à plusieurs heures sinon le risque est de perdre tout lorsque l'on écrit un texte long et que l'on va prendre un café !

**Comment by MattLUnLille** [comment]
Je précise que j'étais sur une page quelconque de ce portfolio - soit "KAPC+"  (la page d'accueil du portfolio)/"Mon profil et consentement"/ ... -, et c'est lorsque j'ai cliqué, après un certain temps d'inactivité donc, sur "Mes bilans par compétence"-> "Compétences personnalisées" ->"Libellé de la compétence personnalisée (à modifier)" que ce bug est survenu.
Et qu'après en cliquant sur que ce soit "Mon profil ..."/"Mes formations ..."/ ... , les différentes pages étaient apparues vides de contenu après que le message d'erreur de ma capture d'écran s'affiche en premier et que je le ferme.
Voilà pour la description complète, je m'améliorerai niveau précisions, promis.

Bonne journée et bon courage, en espérant que cette remontée ait servie

**Comment by olivier-gerbe** [comment]
Oui, au bout de 30mn, on est déconnecté automatiquement par Tomcat si il n'y a pas d'activités.

**Comment by MattLUnLille** [comment]
Merci pour la prise en compte de ce bug et vos réponses et éclairages techniques, @olivier-gerbe et @jgribonvald.
