### ISSUE TITLE
Personnalisation adresse mail "Ma Synthèse"

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#50]
L'adresse mail étudiante est directement reprise dans "Ma Synthèse". Est-ce que l'on peut laisser à l'étudiant le choix de modifier cette adresse mail ?
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/c404b466-d0d5-408a-9e85-8a13689b34b8)

On pourrait avoir des demandes de ce genre, après vu que c'est une **base** de CV on pourra répondre que ces personnalisations seront à faire en dehors de Karuta.

@giraudin

**Comment by isabelle-roy** [comment]
Si c'est ce que vous voulez, techniquement c'est possible. Mais ça va changer l'adresse dans la page Me connaître :

![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/79ea3de8-f54b-4842-bc99-7a8bd3290592)

Dites-moi si vous voulez que je procède.

**Comment by giraudin** [comment]
Bonsoir, OK pour changer aux 2 endroits ! 

Le 29 mai 2024, 16:34, à 16:34, Isabelle Roy ***@***.***> a écrit:

**Comment by isabelle-roy** [comment]
Ok, fait sur le serveur ePortfolium.
Sera livré avec la prochaine version sur nextcloud.

**Comment by AdrienPrugnaud** [comment]
@AdrienPrugnaud A tester

**Comment by AdrienPrugnaud** [comment]
Fait
