### ISSUE TITLE
Texte gris, vert... pour les carrés correspondent au "Apprentissages critiques mobilisés"

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#53]
Désormais les textes "non mobilisé", "bien mobilisé" n'apparaissent plus quand on passe le curseur sur le carré de couleur. On voit gris, vert... (ce qui est bien pour les daltoniens) mais cela perd son sens pour les utilisateurs quand on voit juste gris, vert...: 

![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/d4a13a70-be97-481d-85e7-e0480bcf5da9)

![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/a9efba38-e53e-40aa-bb84-eb83eed129b7)

**La solution serait :** 
- mettre le texte "non mobilisé" ancré de base ce qui donnerait : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/aa4a9812-8fdb-4751-8516-e90b7edad4c8)

- quand on passe le curseur sur le carré de couleur, on voit le nom de la couleur : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/d133b3ad-ed16-4f1d-9096-d3195ad482d8)

Qu'en penses-tu ? @giraudin

**Comment by isabelle-roy** [comment]
Petite note additionnelle : l'écran d'Adrien semble très large, sur un écran de laptop régulier ça donne ceci :

![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/ac44a5d0-c674-4827-9987-486644771832)

Pas beaucoup de place pour du long texte ancré, d'où je pense est venu le nom des couleurs seulement.

Même avec juste la couleur des fois je déborde dans la colonne de droite :

![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/47eff294-7714-4b7d-a202-858b619e07c0)

Par contre le gris n'est pas visible du tout.

**Comment by giraudin** [comment]
Ca me parait compliqué vu les retours d'Isabelle. je propose de laisser tomber, et de laisser comme c'était avant
