### ISSUE TITLE
Actions et traces de l'étudiant les enseignants ne sont pas proposés comme évaluateurs des apprentissages critiques

### ISSUE THREAD

**Issue by marusmb** [avenirs-esr/GT-Test#54]
Lors de la création d'un "stage et alternance" ou d'une "autre action", pour les apprentissages critiques l'étudiant peut choisir comme évaluateur "auto-évaluation", "par un pair" ou "par un tuteur pro". Il n'y a pas la possibilité de choisir l'évaluation par le où les enseignants.

**Comment by giraudin** [comment]
marusmb ***@***.***> a écrit :﻿
Lors de la création d'un "stage et alternance" ou d'une "autre action", pour les apprentissages critiques l'étudiant peut choisir comme évaluateur "auto-évaluation", "par un pair" ou "par un tuteur pro". Il n'y a pas la possibilité de choisir l'évaluation par le où les enseignants.

Eric :
C’était à l’origine une demande des enseignants de ne pas y apparaître, comme pour les saés, afin de ne pas avoir à effectuer 50 évaluations et 50 clics sur une page.Après on peut proposer de les rajouter si ça ne retarde pas la sortie de kapc 1.4 déjà très en retard.

**Comment by marusmb** [comment]
Pour les SAés les enseignants font parti de la liste
![image](https://github.com/avenirs-esr/GT-Test/assets/160909485/abcb3a7f-bf72-49c2-b0cc-434549bd550e)

**Comment by isabelle-roy** [comment]
Arrêtez de nous demander des changements : quand vous avez demandé à Olivier d'ajouter les enseignants dans les AC des SAés après que j'ai livré KAPC 1.4, cela a introduit un bug ! À ce stade on ne corrige que les bugs.

**Comment by giraudin** [comment]
Je suis d'accord avec toi Isabelle.

En alternance et stage de toutes façons c'est le tuteur pro qui est le plus en contact avec l'étudiant donc pas grave. Ne pas rajouter donc les enseignants. Ça va retarder.

**Comment by AdrienPrugnaud** [comment]
A fermé
