### ISSUE TITLE
Rajouter informations supplémentaire dans les portfolios "FORMULAIRES" et "QUICKSTART"

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#55]
Dans le bandeau bleu des portfolios "FORMULAIRES" et "QUICKSTART" enlever l'image et mettre un texte indiquant les prérequis à suivre : 
- Créer les comptes et portfolios enseignants dans le module Compétences
- Créer les comptes et portfolios en compétences des étudiants dans le module Compétences
- Créer les comptes conseillers PP dans le module PP
- Créer portfolios étudiants PP dans le module PP
- Supprimer les portfolios étudiants PP dans le module PP
- Supprimer les comptes conseillers PP dans le module PP
- Supprimer les comptes et portfolios en compétences étudiants dans le module Compétences
- Supprimer les comptes et portfolios enseignants dans le module Compétences.

Il est important de respecter l'ordre des opérations :
Créations : module Compétences -> module PP
Suppressions : module PP -> module Compétences

On va regarder ensemble avec @isabelle-roy

**Comment by AdrienPrugnaud** [comment]
Fait : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/e3f333b7-b3de-490e-ae1b-8a5e88e421fb)
Ce vous convient ? @giraudin @isamath
Est-ce qu'il ne faut pas aussi le rajouter dans le portfolio "QUICKSTART" ? @isabelle-roy

**Comment by Isamath** [comment]
Moi je mettrais :


FORMULAIRES APC  (a gauche)                        FORMULAIRES APC + PROJET DE VIE (à droite)



et oui je pense qu'il faut aussi le rajouter sur Quickstart






[1711620532714]
Isabelle Mathieu- Accompagnatrice pédagogique DREAM-U Phone : 0413946220
E-mail : ***@***.******@***.***>
Centre d'Innovation Pédagogique  - Direction de la Formation
Campus Aix-en-Provence – Bâtiment Pouillon - Bureau 101 -


________________________________
De : AdrienPrugnaud ***@***.***>
Envoyé : mardi 18 juin 2024 11:08:12
À : avenirs-esr/GT-Test
Cc : MATHIEU Isabelle; Mention
Objet : Re: [avenirs-esr/GT-Test] Rajouter informations supplémentaire dans les portfolios "FORMULAIRES" et "QUICKSTART" (Issue #55)


Ce mail provient de l'extérieur, restons vigilants

Fait :
image.png (view on web)<https://github.com/avenirs-esr/GT-Test/assets/97050678/e3f333b7-b3de-490e-ae1b-8a5e88e421fb>
Ce vous convient ? @giraudin<https://github.com/giraudin> @Isamath<https://github.com/Isamath>
Est-ce qu'il ne faut pas aussi le rajouter dans le portfolio "QUICKSTART" ? @isabelle-roy<https://github.com/isabelle-roy>

**Comment by isabelle-roy** [comment]
Je l'ai mis à gauche parce que c'est celui qui doit absolument être lu (le texte à droite n'est pas important, c'est juste du blabla). Peut-être si j'ajoute une ligne blanche entre les deux...
Et j'ai oublié le Quickstart, je vais corriger.
Par contre je ne suis pas encore convaincue que c'est là que ce texte doit aller...

**Comment by isabelle-roy** [comment]
![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/f3e60f40-10a6-40b6-9ebf-c54775aabe3c)

![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/a52c20da-fc23-46b6-b096-db83cb6d3f29)

**Comment by isabelle-roy** [comment]
Oups, j'ai oublié quelque chose au bas de la page d'accueil dans ce que je vous ai livré hier :(
Je viens de le retirer dans la version que je suis en train de retravailler.

**Comment by isabelle-roy** [comment]
![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/a22442c9-c6a9-4c5f-9a36-fac497e03f12)

![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/8261e948-57e3-4651-b8af-eb363db30a54)

**Comment by AdrienPrugnaud** [comment]
Avec les deux couleurs cela me convient aussi, comme tu dis le plus important c'est la partie de gauche.
Cela vous convient @Isamath et @giraudin ?

**Comment by Isamath** [comment]
ok pour moi
même si j'aurais mis en gras
 **La création des comptes ...** et de la même façon 
**La suppression des comptes doit respecter ...**

**Comment by isabelle-roy** [comment]
Allo Isabelle, je ne suis pas certaine de comprendre : est-ce que je change la phrase ou est-ce que je fais deux listes ?

![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/423bd3db-f6c6-460a-a0d7-4b6b83d26ca0)

**Comment by isabelle-roy** [comment]
Issues #55 #56 et #57 : nouvelle version déposée sur NextCloud.

**Comment by Isamath** [comment]
Moi je ferai 2 listes : la création et la suppression

Envoyé à partir de Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Isabelle Roy ***@***.***>
Envoyé : Thursday, June 20, 2024 4:51:16 PM
À : avenirs-esr/GT-Test ***@***.***>
Cc : Isamath ***@***.***>; Mention ***@***.***>
Objet : Re: [avenirs-esr/GT-Test] Rajouter informations supplémentaire dans les portfolios "FORMULAIRES" et "QUICKSTART" (Issue #55)


Ce mail provient de l'extérieur, restons vigilants

Allo Isabelle, je ne suis pas certaine de comprendre : est-ce que je change la phrase ou est-ce que je fais deux listes ?

**Comment by isabelle-roy** [comment]
Deux listes :
![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/5e359ff7-0f38-4700-9e76-20685841ffdd)

**Comment by marusmb** [comment]
C'est ok pour moi avec la version des zip du 20/06.

**Comment by AdrienPrugnaud** [comment]
A valider par @AdrienPrugnaud

**Comment by AdrienPrugnaud** [comment]
Fait
