### ISSUE TITLE
Problème emplacement "Finaliser" dans les bilans de compétences

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#56]
Dans les bilans de compétences l'étudiant ajoute plusieurs sections évaluations.
L'étudiant en ajoute deux mais ajoute l'évaluation par enseignant seulement sur la première puis il fait une demande d'évaluation : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/88d24fed-811e-4a26-8b58-104cdd81c0f3)

Dans le tableau de bord de l'enseignant, l'enseignant peut voir et finaliser les deux sections même si pour la deuxième il n'y a pas eu de demande d'évaluation et qu'il ne peut pas mettre de note : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/0881fb14-2158-40e5-9b87-2d6c4cbf1ac0)

Si l'enseignant clique sur "finaliser" dans la section où il devrait rien y avoir, la compétence est considéré comme évaluée et passe dans les "Compétences Evaluées" : 

https://github.com/avenirs-esr/GT-Test/assets/97050678/993be5f9-87a5-4573-903c-a1db3da26230

De plus quand on retourne dans le portfolio étudiant (avec le rôle étudiant) l'étudiant peut faire ces actions : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/840929be-8d52-4dd1-b17b-6660c7911733)

 @olivier-gerbe @isabelle-roy

**Comment by isabelle-roy** [comment]
Je ne pense pas qu'avec Karuta on puisse faire autrement. Mais normalement dans la vrai vie les étudiants vont faire valider un niveau avant de faire valider le suivant (pas deux niveaux en même temps pour la même compétence...)
Version industrielle ?

**Comment by isabelle-roy** [comment]
@olivier-gerbe 
il me semble que tu avais corrigé ça déjà...

**Comment by olivier-gerbe** [comment]
J'ai ajouté un test pour le menu. Il faut qu'il y ait une date-de-eval pour voir finaliser. Fait sur KPAC14
@isabelle-roy À transférer sur NextCloud

**Comment by isabelle-roy** [comment]
Issues #55 #56 et #57 : nouvelle version déposée sur NextCloud.

**Comment by marusmb** [comment]
C'est ok pour moi avec la version des zip du 20/06.

**Comment by AdrienPrugnaud** [comment]
Ok corrigé
