### ISSUE TITLE
Tri sur la liste "Feedback répondus - SAés" non opérationnel

### ISSUE THREAD

**Issue by marusmb** [avenirs-esr/GT-Test#57]
Un enseignant vient de me remonter qu'il n'était pas possible de trier la liste des feedback répondus pour les SAés. 
J'ai fait des essais pour les deux versions 1.3.5 et 1.4 les boutons de tris ne sont pas fonctionnels sur cette liste.
Je ne pense pas que cela nécessite de refaire une nouvelle livraison, de plus je n'ai pas testé toutes les listes.

**Comment by isabelle-roy** [comment]
Allo Michel, 
L'enseignant est sur 1.3.5 ? (Ce que vous avez actuellement en production avec les étudiants à l'USMB ?) 
Isabelle

**Comment by isabelle-roy** [comment]
Je viens de tester chez nous sur 1.3.5 et sur 1.4 et effectivement les tris ne fonctionnent plus sur les en-tête de ce tableau.
La dernière modification sur ce tableau a été quand il y a eu une demande pour ajouter la poubelle en fin de ligne.
@olivier-gerbe est-ce que tu peux regarder ? (chez nous sur 1.4 tu peux utiliser le compte isabelle-ens pour voir)

**Comment by olivier-gerbe** [comment]
Il n'y avait pas de table tribale dans le rapport. C'est corrigé sur KPAC1.4
@isabelle-roy 
Il faudrait le mettre sur Nexcloud.

**Comment by isabelle-roy** [comment]
Issues #55 #56 et #57 : nouvelle version déposée sur NextCloud.

**Comment by marusmb** [comment]
C'est ok pour moi avec la version des zip du 20/06.

**Comment by marusmb** [comment]
ok
