### ISSUE TITLE
Erreur de frappe portfolio enseignant rubrique export des notes

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#58]
Erreur de frappe qui se trouve dans les 4 sous rubrique d'export de notes du tableau de bord enseignant (export des notes de SAé, de stage...) (un t de trop) :
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/0c7d37a2-6956-4aff-9023-3ec8102c7a21)

@isabelle-roy

**Comment by isabelle-roy** [comment]
Corrigé ePortfolium.

**Comment by AdrienPrugnaud** [comment]
A validé

**Comment by AdrienPrugnaud** [comment]
Fait
