### ISSUE TITLE
Erreur page d'accueil portfolio étudiant

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#59]
Erreur ici "personnel" au lieu de "projet" : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/587e85c5-b199-407a-b1eb-3bcca08f09fd)

**Comment by isabelle-roy** [comment]
Adrien je ne comprends pas je n'ai pas ça chez ePortfolium ???
J'ai voulu ajouter "projet" avant "personnel" mais j'ai trouvé ça :
![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/b1a88fc9-28aa-42b2-8007-c9eb7e9385f1)
???

**Comment by AdrienPrugnaud** [comment]
Bonjour Isabelle, c'était une erreur de ma part (mauvais serveur) du coup j'avais fermé l'issue, désolé.
