### ISSUE TITLE
Bug lié à la déconnexion du profil et sa reconnexion malgré le fait d'avoir vidé le cache - testé sous Firefox (Version 102.13.0esr (64bits)) et PC

### ISSUE THREAD

**Issue by MattLUnLille** [avenirs-esr/GT-Test#6]
Bonjour,

Je viens à l'instant de quitter ma session "Enseignant" via le login "ens.lille", en me déconnectant donc, sous Firefox et sur mon PC Portable pro.
Malgré le fait d'avoir vidé le cache (cf. pj), puis d'avoir actualisé la page courante via le bouton situé en haut à gauche du navigateur : 
![Capture d’écran 2023-07-19 163747](https://github.com/avenirs-esr/GT-Test/assets/139477155/c272c822-c8cd-4523-bc38-a700e672d662)
Lorsque je clique à nouveau sur "Entrez!", et ce malgré un temps d'attente raisonnable de quelques minutes avant de recliquer sur ce même bouton, je me retrouve sur ma session d'enseignant, et non au choix de session possible pour pouvoir choisir celle d'étudiant par exemple.

Edit :  J'ai beau réessayer plusieurs fois en ce moment : rien à faire je reste sur mon profil quitté à l'instant d'enseignant, alors que je ne rencontrais aucun problème pour changer de profil ainsi au préalable jusqu'à ce Mercredi matin.

**Comment by AdrienPrugnaud** [comment]
Bonjour,
Mince, dans ce cas on peut utiliser un outil comme ccleaner pour être certains d'avoir l'ensemble des traces et historiques de supprimés ou bien encore ouvrir une page en navigation privée pour se connecter avec un autre profil

**Comment by MattLUnLille** [comment]
Merci pour ta réponse et les solutions techniques en cas de retour éventuel de ce bug, @AdrienPrugnaud
