### ISSUE TITLE
Batch revalidation des CGU ne fonctionne pas

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#60]
J'ai fait le test pour faire revalider un doc de CGU aux étudiants et cela ne fonctionne pas (l'ajout du document n'est pas pris en compte) : 

https://github.com/avenirs-esr/GT-Test/assets/97050678/db0ffcaf-611d-47c7-bcf2-9afc92369622

Le document n'apparaît pas : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/1d334a1e-f3d6-4a8b-b0b5-d82789289075)
et quand l'étudiant veut cliquer sur "j'ai pris connaissance..." : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/160cd6b6-85b9-49a3-8f08-ea1ecdb28f6e)
donc impossible de continuer à utiliser le portfolio.

(j'ai aussi pris le docx dispo dans "Mettre à jour le fichier RGPD dans le modèle de portfolio étudiant" mais même résultat)

@isabelle-roy 
@olivier-gerbe

**Comment by isabelle-roy** [comment]
Allo Adrien, je ne savais pas que ce batch là existait, ça doit être Olivier qui l'a créé, je vais le laisser regarder. Isabelle

**Comment by isabelle-roy** [comment]
Adrien je viens de tester sur notre serveur et ça fonctionne, penses-tu qu'on pourrait se rencontrer pour que je voie ce qui se passe chez toi ?

**Comment by marusmb** [comment]
Ça fonctionne également de mon côté.

**Comment by marusmb** [comment]
J'ai omis de préciser que c'était avec la version des zip du 20/06

**Comment by isabelle-roy** [comment]
@olivier-gerbe 
Je viens de tester avec Adrien sur son serveur. Le problème n'est pas le batch d'ajout de CJU.
Sur le serveur d'Adrien, on ne peut pas uploader de document Word dans un élément Karuta Document - seulement les document PDF sont enregistrés dans les éléments Documents. (Je n'ai pas ce problème chez eportfolium)

**Comment by AdrienPrugnaud** [comment]
Corrigé, cela venait du choix du fichier présent dans "Mettre à jour le fichier RGPD dans le modèle de portfolio étudiant" qui était vide.
Olivier a corrigé en redéposant le fichier

**Comment by AdrienPrugnaud** [comment]
Fait
