### ISSUE TITLE
Demandes de feedbacks qui n'apparaissent pas dans le tableau de bord enseignant

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#61]
Je viens de réaliser une demande de feedback, puis une demande d'évaluation concernant une compétence et une compétence personnalisé mais dans le tableau de bord enseignant je vois seulement les demandes d'évaluations mais pas celles de feedbacks : 
![mtQP9vj](https://github.com/avenirs-esr/GT-Test/assets/97050678/34703d73-cd56-426f-9a96-bb5d0dd259b1)

j'ai aussi essayé de faire seulement une demande de feedback mais elle n'apparait pas dans le tableau de bord : 
Voici la demande : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/4d972096-4cef-4e35-a6c6-4ecda997d687)
Voici le tableau de bord de l'enseignant : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/6ff49bed-113b-4746-be6a-c979f4d11a98)

@olivier-gerbe 
@isabelle-roy

**Comment by isabelle-roy** [comment]
Allo Adrien, je suis incapable de reproduire le problème sur notre serveur. Est-ce que tu veux qu'on se rencontre pour que tu me montre ce qui se passe ? 

Par contre @olivier-gerbe l'étudiant **a le bouton pour réévaluer** et le bouton pour demander l'évaluation ne disparait jamais :
![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/d6119d9a-a2fc-4b98-825e-e9a2a9f492b7)
serveur ePortfolium kapc 1.4 comptes isabelle-etu et isabelle-ens

**Comment by olivier-gerbe** [comment]
@isabelle-roy 
Pas capable de reproduire voir kapc1.4 isabelle-et

**Comment by marusmb** [comment]
Pour moi cela fonctionne bien avec la version des zip du 20/06.

**Comment by AdrienPrugnaud** [comment]
Corrigé

**Comment by isabelle-roy** [comment]
Information additionnelle aux testeurs : pour que la demande de feedback soit envoyée, il faut absolument modifier la question !!
