### ISSUE TITLE
Impossibilité de redemander une demande de feedback pour une compétence

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#63]
Quand l'enseignant finalise une première évaluation sur la page compétence, l'étudiant perd la possibilité de redemander des  feedbacks : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/369c9dc8-e27c-4b5f-9ce5-6e09a7886a70)

@olivier-gerbe

**Comment by marusmb** [comment]
Je confirme, j'ai le même comportement.

**Comment by AdrienPrugnaud** [comment]
A tester

**Comment by AdrienPrugnaud** [comment]
Fait
