### ISSUE TITLE
Impossibilité de re-choisir une formation sur la page d'accueil

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#64]
Quand on clique sur la sélection de la formation sur la page d'accueil, si on clique sur le bandeau noir on ne peut plus resélectionner la formation. Cela peut-être problématique pour les étudiants qui suivent deux formation ou bien lorsqu'un bug apparaît et qu'il n'y a pas de formation de sélectionnée par défaut : 

![Sélection](https://github.com/avenirs-esr/GT-Test/assets/97050678/4cef5fbc-4d15-4c6c-a608-402a876f449d)

 @isabelle-roy @olivier-gerbe

**Comment by isabelle-roy** [comment]
Allo Adrien, 
On ne peut pas faire autrement dans Karuta, c'est déjà un gros bypass pour qu'il y ait quelque chose là tant que la section formations actuelles est vide : il faut absolument que l'étudiant ajoute sa formation dans ses formations actuelles pour faire des changements. C'est écrit dans la bulle info que la liste c'est celle de sa page formation actuelle mais c'est peut-être pas clair parce qu'il y a un paquet d'infos importantes là-dedans. Si tu veux on peut ajouter plus d'infos dans la bulle info : dis-moi quoi. 
Isabelle

![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/de068f1c-9558-4526-975e-52e11a9c0a45)

**Comment by isabelle-roy** [comment]
Voici ce que je propose :

![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/97ef1672-ff19-4b2a-ae1e-837d4cc59b45)

**Comment by AdrienPrugnaud** [comment]
Ou alors mettre ces informations dans le dur et pas dans une bulle d'aide ? Car les étudiants vont croire à un bug et ne vont pas penser à regarder la bulle d'aide

**Comment by isabelle-roy** [comment]
Tu penses vraiment que les étudiants vont aller essayer de changer leur formation sur la page d'accueil ?
Avant d'avoir rempli leurs formations actuelles ?
Tous les enseignants sont formés à dire à leurs étudiants que la chose numéro 1 à faire dans le portfolio c'est renseigner la section Mes formations actuelles en toute priorité....
Tu veux qu'on se parle sur en visio plutôt que sur GitHub ?

**Comment by isabelle-roy** [comment]
![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/1ccbb165-6424-4286-8815-6b514876dbd6)

![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/22571263-3a4a-4a1a-93ad-25a3928bc757)

**Comment by isabelle-roy** [comment]
Est-ce qu'il y a d'autres places comme ça où c'est pas clair ?
Il y a des pages du portfolio qui sont tellement chargées d'informations !!

**Comment by AdrienPrugnaud** [comment]
Ce que tu as fait me convient parfaitement. 
A la limite mettre (c'est du détail) : Cette liste contient seulement les formations que vous avez ajoutées dans la section "Mes formations et référentiels" de votre ePortfolio

**Comment by isabelle-roy** [comment]
![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/d577ea68-1564-4f0c-8d8d-738f5ae07bdb)

**Comment by AdrienPrugnaud** [comment]
Fait
