### ISSUE TITLE
Un enseignant ne peut pas supprimer les demandes de feedback du projet de vie

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#65]
Dans le tableau de bord de l'enseignant concernant le projet de vie "Demande de feedbacks - Projet Pro" il y a une poubelle permettant de supprimer les demandes de feedbacks, quand je clique dessus rien ne se passe : 
![jOAKgV2](https://github.com/avenirs-esr/GT-Test/assets/97050678/37e6c1f1-4627-4d51-9577-d0970350548b)
Par contre j'arrive bien à supprimé dans "Feedbacks répondus - Projet Pro" : 
![Test](https://github.com/avenirs-esr/GT-Test/assets/97050678/cd51b3d5-ee05-422f-8dfe-ae2404f393e4)

Mais l'étudiant peut refaire partir la demande supprimée : 
![Suppression](https://github.com/avenirs-esr/GT-Test/assets/97050678/0648ab54-e3ac-43c6-a883-c85b4bddcaa7)
et l'enseignant ne peut plus rien faire : 
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/fd7b563b-7766-4383-8fdb-b17d85621d73)

Vous pouvez tester sur : https://test.recia.dev/recia-insa/karuta/htm/karuta.htm
avec le compte : 
etu.brest et ens.brest
mdp : testversionkapc+

@isabelle-roy @olivier-gerbe

**Comment by isabelle-roy** [comment]
Allo @olivier-gerbe,

J'ai testé chez nous:
Nous aussi la ligne ne disparait pas dans le tableau de l'enseignant mais ça reste en suspend chez l'étudiant (pas de bouton pour renvoyer la demande) :

![image](https://github.com/avenirs-esr/GT-Test/assets/1541128/a4707de0-f36b-497c-aa82-33dba8ad6676)

Bref chez nous, la poubelle ne fait absolument rien, la demande demeurre en attente et l'enseignant peut toujours répondre.

Pour tester chez nous les comptes c'est isabelle-etu et isabelle-ens.
Ma demande test est au bas de la page Me connaître (Question "Test issue #65").

**Comment by olivier-gerbe** [comment]
Effectivement, les poubelles ne peuvent pas marcher dans les rapports de projet de vie. Pour que cela fonctionne, il y aurait plusieurs heures de travail pour ajouter tous les tag sémantiques de projet de vie dans les choix possibles pour Laguiole table vecteur.
Je propose donc de retirer les poubelles pour la version 1.4. D'autant plus que, comme le fait remarquer Isabelle, ce n'est pas clair du coté étudiant.

**Comment by AdrienPrugnaud** [comment]
Merci pour votre retour, vous confirmez @giraudin @jgribonvald ? Je ne sais pas qui avait fait cette demande

**Comment by olivier-gerbe** [comment]
Je viens de revérifier. J'ai ajouté une ligne dans le fichier js : fonctions-apc14.js
Cela supprime bien la demande mais cela ne règle pas le problème dans le portfolio étudiant car cela marque en attente mais  il n'y aura jamais de réponse.

**Comment by AdrienPrugnaud** [comment]
Fait
