### ISSUE TITLE
Changement de nom du "Tableau de bord du conseiller"

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#66]
Pour que le nom soit un peu moins impersonnel est-ce qu'il ne serait pas judicieux de changer "Tableau de bord du conseiller" en "Tableau de bord conseiller" ?
![image](https://github.com/avenirs-esr/GT-Test/assets/97050678/b1dc7e95-1371-43fb-85f8-490f9891a2d6)

A voir si le changement est trop complexe.

Qu'en pensez-vous @giraudin @jgribonvald @isamath ?

**Comment by giraudin** [comment]
oui

**Comment by AdrienPrugnaud** [comment]
@olivier-gerbe serait-il possible de changer le nom stp

**Comment by olivier-gerbe** [comment]
Fait sur notre instance KAPC14

**Comment by AdrienPrugnaud** [comment]
Si c'est bon, à inclure dans la prochaine livraison

**Comment by AdrienPrugnaud** [comment]
@olivier-gerbe J'ai toujours le même nom, si c'est trop complexe on laisse comme avant

**Comment by olivier-gerbe** [comment]
Est-ce que c'est pour un nouveau conseiller car j'ai changé dans le batch

**Comment by olivier-gerbe** [comment]
Comme il n'y a qu'une instance du portfolio conseiller, comme il a déjà été créé, il faut changer son libellé à la main.

**Comment by AdrienPrugnaud** [comment]
@olivier-gerbe 
C'était pour un nouveau conseiller (je suis reparti d'une installation de zéro). 
Je viens de refaire le test en supprimant et recréant et j'ai toujours le même nom pour le portfolio : 
![image](https://github.com/user-attachments/assets/43b330a9-f3ad-4e79-9ad4-bd425cc13b4a)

**Comment by olivier-gerbe** [comment]
justement c'est bon 
"Pour que le nom soit un peu moins impersonnel est-ce qu'il ne serait pas judicieux de changer "Tableau de bord du conseiller" en "Tableau de bord conseiller" ?"

**Comment by AdrienPrugnaud** [comment]
mince désolé... c'est bon
