### ISSUE TITLE
Demande de feedbacks n'apparaissent pas dans le tableau de bord enseignant

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#67]
Les demandes de feedbacks n'apparaissent pas pour les SAés, stages et autres actions : 
![image](https://github.com/user-attachments/assets/1983ab37-c681-4039-8f2a-b851f2145f11)
![image](https://github.com/user-attachments/assets/9078aaed-82a7-4934-8843-e9e33ddde0a1)

Pour tester : https://test.recia.dev/recia-insa
Id : ens.brest1
Mdp : testversionkapc+

@olivier-gerbe @isabelle-roy

**Comment by olivier-gerbe** [comment]
je peux avoir id et mdr de l'étudiant ?

**Comment by olivier-gerbe** [comment]
Je n'ai pas réussi à reproduire. Je me suis logué comme étudiant j'ai demandé un feedback et il apparait bien.

**Comment by AdrienPrugnaud** [comment]
Re @olivier-gerbe , c'est de ma faute je n'avais pas personnalisé le message du feedback en tant qu'étudiant (du coup il ne part) pas correctement. 
Je viens de tester pour les SAés, stages et autre actions quand l'enseignant valide son évaluation, la demande de feedback ne disparait plus automatiquement comment avant.

**Comment by olivier-gerbe** [comment]
Bonjour Julien,
Il manquait la ligne qui efface toutes les demandes de la page dans le fichier JS. J'ai déposé une nouvelle version de karuta-configuration-tech sur Nextcloud dans 1.4 - À utiliser pour les tests

**Comment by AdrienPrugnaud** [comment]
Corrigé
