### ISSUE TITLE
Dans "Mes autres actions" l'évaluation d'une compétence ne peut pas être réalisée par un enseignant

### ISSUE THREAD

**Issue by marusmb** [avenirs-esr/GT-Test#68]
Dans "Mes actions et traces -> Mes actions -> Mes autres actions", il n'est pas possible de demander l'évaluation d'un apprentissage critique par un enseignant. On a choix que étudiant - pair - ou tuteur, que ce soit pour une compétence de la formation ou personnalisée.
![image](https://github.com/user-attachments/assets/c93dcae1-c182-4431-b307-1271c035ce30)

**Comment by AdrienPrugnaud** [comment]
@isabelle-roy @olivier-gerbe

**Comment by olivier-gerbe** [comment]
Est-ce que cela avait été demandé?

**Comment by giraudin** [comment]
non

**Comment by giraudin** [comment]
Attention ce n'est pas l'évaluation d'une compétence mais d'un apprentissage critique dont on parle
