### ISSUE TITLE
Dans "Mes autres actions" évaluation impossible par un pair

### ISSUE THREAD

**Issue by marusmb** [avenirs-esr/GT-Test#69]
L'étudiant peut demander d'être évalué par un pair, le pair reçoit l'action en revanche il ne peut rien évaluer apprentissage critique ou globalité.

**Comment by AdrienPrugnaud** [comment]
@isabelle-roy @olivier-gerbe

**Comment by AdrienPrugnaud** [comment]
Re @marusmb pourrais-tu déposé une capture d'écran stp ?
J'ai testé et pour moi cela fonctionne mais on parle peut-être pas de la même chose : 
![image](https://github.com/user-attachments/assets/d6606364-3969-4743-8cf7-1ba2238b69d0)
![image](https://github.com/user-attachments/assets/a0f3d78e-a680-4193-a110-e0df4fa233d4)

**Comment by giraudin** [comment]
J'ai testé, ça marche sans problème pour une saé avec évaluateurs choisis par l'étudiant mais pour une sae avec évaluateurs choisis par l'enseignant, que ce soit pour les pairs ou les tuteurs pro, ils peuvent évaluer mais pas soumettre l'évaluation globale de la saé. Ils n'ont pas de bouton envoyer.

Voir capture (piste : attention l'étudiant etueric1 a demandé à la fois une éval par un pair etueric2, par un tuteur pro et par un enseignant)

![image](https://github.com/user-attachments/assets/ec5619cc-631f-418d-be38-51cc54d363da)

**Comment by AdrienPrugnaud** [comment]
@olivier-gerbe j'ai l'impression que le bug apparait quand on fait plusieurs demandes sur la même adresse mail
@giraudin tu peux tester de faire la demande concernant une sae avec évaluateurs choisis par l'enseignant à une autre adresse mail stp
+ cela ne fonctionne pas si on partage et en tuteur pro et en pair à une même adresse (le bug pourrait aussi venir de là mais dans ce cas là se serait normal)

**Comment by giraudin** [comment]
> @olivier-gerbe j'ai l'impression que le bug apparait quand on fait plusieurs demandes sur la même adresse mail @giraudin tu peux tester de faire la demande concernant une sae avec évaluateurs choisis par l'enseignant à une autre adresse mail stp
> 
>     * cela ne fonctionne pas si on partage et en tuteur pro et en pair à une même adresse (le bug pourrait aussi venir de là mais dans ce cas là se serait normal)

Non ce n'est pas ce que j'ai fait j'ai bien une adresse mail différente pour le pair et le pro et je n'utilise qu'un seul pair, toujours le même pair pour 2 saé différentes (ce qui est un cas possible de la vraie vie)

**Comment by AdrienPrugnaud** [comment]
@olivier-gerbe @giraudin 
j'ai trouvé le bug, quand l'étudiant ne fait pas de demande d'évaluation à un enseignant, on a bien le bouton "envoyer" aussi bien pour les SAés choix d'évaluateur par un enseignant que par l'étudiant : 
![image](https://github.com/user-attachments/assets/98b0573e-7988-4544-851b-c91f6f9cf09e)

Par contre, dès que l'étudiant fait une demande d'évaluation à un enseignant le bouton disparait : 
![image](https://github.com/user-attachments/assets/f8c809df-5a2f-4142-a16f-0774433cf4a7)

C'est la même chose pour toutes les actions (SAés, stages et autres actions aussi bien pour ceux créés, importés, choix d'évaluateurs étudiants et enseignants) et aussi bien pour le rôle tuteur que pair.

**Comment by giraudin** [comment]
J'en arrive à la même conclusion le pb vient que l'étudiant fait une demande d'évaluation à un enseignant ça supprime les boutons envoyer pour le tuteur pro et le pair

**Comment by olivier-gerbe** [comment]
Oui la demande d'évaluation fige la SAE. Ce comportement me semble normal, l'enseignant doit évaluer quelque chose qui ne doit plus changer.

**Comment by AdrienPrugnaud** [comment]
@giraudin est-ce que tu valides ?

**Comment by isabelle-roy** [comment]
Je vous rappelle que vous nous avez demandé que l'étudiant ne puisse plus modifier la page après avoir demandé l'évaluation à l'enseignant. Donc on gèle toute la page. Effet de bord, c'est gelé pour tout le monde. À considérer pour la version industrielle : geler uniquement pour le rôle étudiant ?

**Comment by giraudin** [comment]
Oui comportement normal sauf qu’en réalité le pair et le pro peuvent quand même évaluer même sans le bouton envoyer et ça modifie sur la page action de l’étudiant.

1) Donc soit on laisse le bouton envoyer pour le pair et le pro et tant que l'enseignant ne finalise pas l'évaluation ces 2 rôles ils peuvent envoyer leur évaluation (je pense que ce serait le mieux car de toutes façons ils peuvent en réalité évaluer mais pas envoyer)

ou

2) On fige aussi le pair et le pro afin qu'ils ne puissent pas modifier l'évaluation mais dans ce cas ils vont penser qu'ils ont un bug si ils cliquent sur le lien qu'ils ont reçu pour évaluer et que rien n'est possible pour eux

**Comment by AdrienPrugnaud** [comment]
@olivier-gerbe Qu'en penses-tu ?

**Comment by olivier-gerbe** [comment]
On laisse comme c'est et on verra le feedback que l'on aura

**Comment by AdrienPrugnaud** [comment]
On valide
@marusmb tu peux fermer l'issue stp
