### ISSUE TITLE
Bug ajout plusieurs fois éval enseignant sur un apprentissage critique

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#70]
Lorsque l'enseignant créé la SAé (c'est la même chose pour les 2 types de SAés et les 2 types de stages) il peut ajouter plusieurs fois la section évaluation par l'enseignant concernant les apprentissages critiques. Avant la section du choix des évaluations disparaissait quand l'ensemble des éléments étaient ajoutés : 
![Eval enseignant](https://github.com/user-attachments/assets/f3cbe9fc-0dbd-4634-a353-7d7c6c3e30e8)

@olivier-gerbe @isabelle-roy

**Comment by olivier-gerbe** [comment]
Corrigé. Il y avait un faute de frappe dans le test

**Comment by AdrienPrugnaud** [comment]
Fait
