### ISSUE TITLE
Choix évaluation enseignant apprentissage critique dans les stages créés par les étudiants

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#71]
Dans "Mes stages et alternances", il n'est pas possible de demander l'évaluation d'un apprentissage critique par un enseignant dans un stage créé par l'étudiant : 
![image](https://github.com/user-attachments/assets/9a4dd898-f66f-44d4-b9ac-4100e5679ac0)

 Alors que c'est possible dans les stages créés par les enseignants et importés par l'étudiant : 
![image](https://github.com/user-attachments/assets/24411b70-10f5-4fee-bba6-d3632514bcb7)

Il faudrait rajouter l'option pour harmoniser.
@olivier-gerbe @isabelle-roy

**Comment by olivier-gerbe** [comment]
C'est fait

**Comment by isabelle-roy** [comment]
Ça avait été demandé à l'origine que les enseignants ne puissent pas évaluer les apprentissages critiques
Puis vous nous avez demandé de l'ajouter à certains endroit et ça a introduit des bugs ailleurs
On avait convenu qu'on ne l'ajoutais plus aux autres endroits pour ne plus introduire d'autres bugs
Vous tournez en rond : on avait convenu de ne pas l'ajouter il y a presque deux mois

**Comment by AdrienPrugnaud** [comment]
@olivier-gerbe J'ai bien le bouton pour rajouter l'évaluation de l'apprentissage critique par l'enseignant mais quand je clique dessus rien ne se passe (pour les stages et autres actions créées par l'étudiant) : 
![Impossibilité](https://github.com/user-attachments/assets/7a477544-64aa-4506-a543-041b458dcfa4)

**Comment by olivier-gerbe** [comment]
Pas réussi à reproduire

**Comment by AdrienPrugnaud** [comment]
@olivier-gerbe je viens de retester est j'ai le même problème, tu peux constater avec le compte etu.brest dans 
le "Mes stage et alternances => "Test création" 
et dans "Mes autres actions" =>"Test autres actions"

**Comment by olivier-gerbe** [comment]
Je crois que c'est bon cette fois-ci. Comme pour l'autre il y a plusieurs occurrences dans les composantes

**Comment by AdrienPrugnaud** [comment]
Corrigé
