### ISSUE TITLE
Les actions concernant les compétences personnalisées n'apparaissent pas dans le bilan de compétence

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#72]
J'ai créé une compétence personnalisée et quand je la rajoute dans des actions (Stages et autres actions) ces actions n'apparaissent pas dans la synthèse des apprentissages du bilan de la compétence personnalisée : 

https://github.com/user-attachments/assets/eb4f4e01-499e-4974-985b-929b4298b3c6

@olivier-gerbe @isabelle-roy

**Comment by olivier-gerbe** [comment]
Corrigé

**Comment by AdrienPrugnaud** [comment]
Fait
