### ISSUE TITLE
Enlever les boutons "envoyer" au niveau des apprentissages critiques pour les pairs et tuteur pro

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#73]
Comme tu as fait pour les enseignants, enlever le bouton "envoyer" pour les pairs et les tuteurs pro stp (et cela pour les actions : SAés, stages...) : 
![image](https://github.com/user-attachments/assets/4f4d02f4-a06c-47b4-8b1f-f3d0f00c9c74)
![image](https://github.com/user-attachments/assets/f71ea7de-ee0d-489a-ac65-16bbd80a7c96)

@olivier-gerbe

**Comment by olivier-gerbe** [comment]
Fait

**Comment by isabelle-roy** [comment]
Mais non !!!! Ce sont des partages par courriel, il faut absolument, pour des raisons de sécurité, que ce soit soumit, au cas où le courriel serait intercepté. Je vous avais expliqué ça déjà : on tourne en rond ! Vous êtes en train de tout casser !

**Comment by AdrienPrugnaud** [comment]
On en avait déjà parlé et c'était un bouton inutile car quand le pair ou le tuteur pro valide son évaluation finale dans la partie "évaluation" toutes les évaluations des apprentissages critiques sont aussi envoyées .
Cela ne sert à rien de cliquer 1 par 1 sur "envoyer" pour chaque évaluation d'apprentissage critique (on avait eu le cas avec les enseignants et les boutons avaient aussi été enlevés)

**Comment by AdrienPrugnaud** [comment]
@olivier-gerbe je viens de tester avec la nouvelle livraison et j'ai toujours les boutons : 
![image](https://github.com/user-attachments/assets/29125e68-ea2d-4532-9a87-3864fe16df1c)

Et je ne trouve plus en bas le bouton envoyer pour finaliser l'évaluation (c'est le cas pour les SAés et stages choix évaluateur étudiant et enseignants, tous ce qui est créé par l'enseignant) : 
![image](https://github.com/user-attachments/assets/30221f9a-b38f-423b-ad8f-de002d29608d)

Tu peux tester avec les comptes habituels et : 
SAé choix enseignant 2 et SAé choix étudiant 2 
+
Stage choix enseignant 2 et Stage choix étudiant 2

**Comment by olivier-gerbe** [comment]
Oups! Il y a des évaluations à plusieurs endroits. C'est fait

**Comment by AdrienPrugnaud** [comment]
@olivier-gerbe j'ai toujours le même problème par exemple pour les stages et les autres actions : 
![image](https://github.com/user-attachments/assets/3ca972f4-9290-47dd-971f-77aefaa0f886)

**Comment by olivier-gerbe** [comment]
Je crois que cette fois c'est bon. Il y en a à plusieurs endroits dans les composantes.

**Comment by AdrienPrugnaud** [comment]
Fait
