### ISSUE TITLE
Remplacer le fichier des CGU/RGPD dans le "Formulaire Projet de Vie"

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#74]
Comme dans le "Formulaire APC" il faudrait aussi remplacer le fichier des CGU/RGPD dans le "Formulaire Projet de Vie" car il est vide : 
![image](https://github.com/user-attachments/assets/2b89e498-bc6f-4795-b702-70781376fe41)

@olivier-gerbe

**Comment by olivier-gerbe** [comment]
Fait.

**Comment by AdrienPrugnaud** [comment]
Corrigé
