### ISSUE TITLE
Réponses feedbacks projet de vie conseiller externe

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#76]
Quand un conseiller externe reçoit une demande de feedback il peut répondre à l'ensemble des demandes de feedbacks même celles des autres conseiller externe (même celle avec une adresse mail différente). Ici c'était dans la partie "Bâtir mon projet" mais c'est le cas partout : 
![image](https://github.com/user-attachments/assets/ca46603a-40ed-4797-9b99-79808d776d70)

@olivier-gerbe

**Comment by isabelle-roy** [comment]
Allo Olivier, après vérification sur comment on a construit ça, c'est le rôle cons-interne qui a les droits d'éditions sur la réponse. Donc je suppose qu'on avait vérifié avec Éric que n'importe quel conseiller pouvait répondre. Mais ce serait à confirmer avec lui parce que je n'ai pas de souvenirs à ce sujet. 
Éric : est-ce que c'est acceptable si tous les conseillers peuvent répondre ?
@olivier-gerbe @giraudin 

![image](https://github.com/user-attachments/assets/ddef0ac1-0910-497f-99f6-92f193d64411)

**Comment by giraudin** [comment]
Bonjour, de mémoire nous avions fait simple. Autant les enseignants sont spécifiques à une formation et donc seuls ceux de la formation peuvent répondre autant les conseillers internes sont considérés au niveau de l'établissement donc tous peuvent répondre. Je sais que ce n'est pas idéal mais nous n'avons pas le temps d'introduire des conseillers spécifiques par formation ou composantes. Ce sont le.plus souvent des psy EN ou des personnels de SUIOP. Après chaque établissement pourra choisir de ne pas renseigner les conseillers en interne et de communiquer les adresses mail des conseillers comme externes. Ne pas oublier que kapc c un prototype pas de l'industriel.

Le 24 juil. 2024, 16:11, à 16:11, Isabelle Roy ***@***.***> a écrit:

**Comment by giraudin** [comment]
Pour une v 1.4.1 ou ultérieure ?

Ce n'est pas idéal mais pas bloquant.

Côté RGPD c'est limite saut si on averti l'etudiant du fonctionnement.

Si la personne qui reçoit le feedback arrive directement sur la bonne page ça va. Dans la rubrique d'aide il faudra préciser que.ca fonctionne comme.ca :

L''étudiant sur une même page ne fait pas de nouvelle demande de feedback tant qu'il n'a pas de réponse à sa demande en cours





Le 24 juil. 2024, 10:55, à 10:55, AdrienPrugnaud ***@***.***> a écrit:

**Comment by jgribonvald** [comment]
Pour moi c'est clairement un frein à l'usage de la fonctionnalité, personne n'ira utiliser ça avec un tel problème.
Mais on verra si quelqu'un veut faire corriger cette problématique

**Comment by giraudin** [comment]
⁣Au final, il faut clore cette issue et indiquer dans l'aide (ce sera aux établissements de formuler à leur sauce) la mention suivante.

Pour les demandes de feedback, dans mon projet de vie, l'étudiant peut les adresser à des enseignants de sa formation (si la formation à désigné des enseignants référents projet de vie), à des conseillers internes à l'établissement (souvent il s'agit de personnels de service d'orientation et d'insertion pro) et ou à des conseillers externes.

Les conseillers externes n'ont pas de compte dans la plateforme eportfolio Karuta Kapc+. C'est à l'étudiant de décider à qui il souhaite partager une page spécifique de son projet de vie. Pour cela il renseignera l'adresse mail du conseiller externe (qui peut être un proche, un professionnel qu'il a rencontré, un coach privé, etc.).

A noter pour les feedbacks aux conseillers externes : le conseiller qui reçoit la demande n'a accès qu'à la page depuis lequel l'étudiant lui a adressé un feedback. Il faut indiquer à l'étudiant de ne pas adresser, sur une même page de mon projet de vie, une nouvelle demande de feedback à un autre conseiller tant que le 1er conseiller n'y a pas répondu, sinon chacun des deux conseillers pourra répondre à tous les feedbacks de cette même page.

Le 25 juil. 2024, 11:09, à 11:09, Julien Gribonvald ***@***.***> a écrit:
