### ISSUE TITLE
Erreur dans l'association d'enseignants à une formation par batch

### ISSUE THREAD

**Issue by marusmb** [avenirs-esr/GT-Test#77]
L’exécution du batch d'association d'enseignant à une formation se bloque. J'ai repris les données en utilisant le formulaire l'association c'est bien passé. J'ai refait un essai avec le fichier en téléchargeant de nouveau le modèle CSV.

[modele csv associer enseignants formations v1.3(6).csv](https://github.com/user-attachments/files/16360864/modele.csv.associer.enseignants.formations.v1.3.6.csv)

![image](https://github.com/user-attachments/assets/9ae23df3-aa2a-44e4-9f0b-f6cf3c32aa40)

**Comment by AdrienPrugnaud** [comment]
Re @marusmb , 
J'ai regardé ton csv tout me semble correct.
Avant de passer le csv est-ce que la formation BUT-INFO a été créée ? (il faut d'abord créer la formation puis passer le csv sinon il ne pourra pas associer les enseignants à la formation).

**Comment by marusmb** [comment]
Oui la formation était créée, j'ai réussi à associer un enseignant en faisant un copier coller des informations de la première ligne du fichier CSV et ça a fonctionné.

**Comment by AdrienPrugnaud** [comment]
Ok, tout fonctionne correctement ou c'est à partir de la deuxième ligne que cela bloque ?

**Comment by marusmb** [comment]
Ça bloque dès la première ligne. 
En utilisant le formulaire et en faisant un copier coller des informations du fichier CSV, j'ai réussi à créer le compte, donc le problème ne provient pas des informations saisies dans le fichier CSV.

**Comment by AdrienPrugnaud** [comment]
Je viens de retester et tout fonctionne bien, il faut passer d'abord passer le batch de création des enseignants puis le batch d'association.
Test d'enlever le (6) dans le nom du ficher csv ?

**Comment by marusmb** [comment]
Problème résolu. Dans la création de la formation j'ai inversé le libellé et le code. 
Désolé.

**Comment by AdrienPrugnaud** [comment]
Pas de soucis cela arrive :) 
Tu peux clore l'issue stp

**Comment by marusmb** [comment]
clos
