### ISSUE TITLE
Ouverture lien partage par mail qui demande une authentification

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#79]
En navigation privée quand j'ouvre un lien de partage (pair et tuteur pro) la page qui s'ouvre et la page d'authentification. 
Je suis obligé de la fermer puis de rouvrir la page pour arriver au bon endroit : 

https://github.com/user-attachments/assets/b98a42de-5565-4071-8cac-60e5ee43084a

(j'ai bien utilisé une adresse mail différente et qui n'est pas utilisée dans Karuta)

@olivier-gerbe 
@isabelle-roy

**Comment by isabelle-roy** [comment]
Je ne suis pas capable de reproduire - quels comptes/portfolios utilises-tu ?

**Comment by AdrienPrugnaud** [comment]
ok cela à l'air d'être bon
