### ISSUE TITLE
Juste une confirmation demandée - police italique des "stages et alternances" créées par soi-même côté enseignant

### ISSUE THREAD

**Issue by MattLUnLille** [avenirs-esr/GT-Test#8]
Bonjour,

J'ai juste une question quant à la police utilisée lorsque l'on créé un stage et alternance - en cliquant sur le bouton d'ajout "Créer un stage/alternance avec choix des évaluateurs par l'enseignant" - dans "Stages et alternances BUT QLIO" et celui d' "Informatique".
La police utilisée pour marquer la différence entre celle créée par les enseignants et les étudiants est bien, volontairement, l'italique côté enseignant ?
![Capture d’écran 2023-07-20 092303](https://github.com/avenirs-esr/GT-Test/assets/139477155/f0f17697-a8f9-48d6-b966-a9cdcc24e03a)
![Capture d’écran 2023-07-20 092321](https://github.com/avenirs-esr/GT-Test/assets/139477155/1dd21763-3425-471a-b463-f57d35b948a5)

Je vous remercie pour votre confirmation, bonne journée et bon courage à tout le monde.

**Comment by AdrienPrugnaud** [comment]
Bonjour,
La police en italique est utilisée pour faire la différence entre une SAé non publiée qui ne sera pas visible par les étudiants (elle sera en italique) et une SAé publiée qui est visible pour les étudiants (sans l'italique).
Nous avons fait cette distinction pour permettre d'éviter d'avoir des publications de SAés en cours de construction par exemple.

**Comment by MattLUnLille** [comment]
Merci pour ta réponse, @AdrienPrugnaud
