### ISSUE TITLE
Module de migration : problème avec l'évaluation d'une compétence

### ISSUE THREAD

**Issue by isabelle-roy** [avenirs-esr/GT-Test#81]
J'ai parfois un problème au niveau de l'évaluation d'une page compétence qui existait dans le portfolio avant la migration : tout est beau du côté de l'enseignant mais du côté de l'étudiant il a un bouton Réévaluer et le bouton Demander une évaluation sur l'évaluation qui a été finalisée par l'enseignant. (Il a aussi le bouton Supprimer et la date de la demande est effacée...) Est-ce que d'autres ont eu ce problème ?

![image](https://github.com/user-attachments/assets/e1ffe2df-2526-438a-bd83-9a0cf9dec72d)

@olivier-gerbe 
Olivier je pense que je dois ajouter quelque chose par batch mais je ne sais pas quoi ni sur quel élément.
serveur : test ubs
enseigant : carron@univ-ubs.fr (via root)
etudiant : isabelle.roy@gmail.com
compétence : BUT Génie industriel / Maintenir en condition opérationnelle...

**Comment by olivier-gerbe** [comment]
Ceci est dû au fait que les évaluations n'ont plus la même structure. Dans les anciennes il n'y a pas de 'section-etudiant-soumission' sur laquelle sont basés les tests du menu.
Il faudrait tout soumettre au moment de la migration.

**Comment by isabelle-roy** [comment]
@olivier-gerbe 
La section section-etudiant-soumission est là :

![image](https://github.com/user-attachments/assets/78e4aa45-5fc3-4996-a026-82eaf7471060)

Je viens de vérifier : ce bloc d'évaluation n'existait pas dans le portfolio 1.3.5.
Je l'ai ajouté après la migration.

**Comment by isabelle-roy** [comment]
@olivier-gerbe 
Je viens de vérifier : ce bloc d'évaluation n'existait pas dans le portfolio 1.3.5.
Je l'ai ajouté après la migration.
Donc on n'a pas encore trouvé la solution au problème...

**Comment by isabelle-roy** [comment]
@olivier-gerbe 
J'ai finalement trouvé comment reproduire : le problème se pose si l'étudiant importe la composante pour l'évaluation de l'enseignant mais ne demande pas l'évaluation. Puis l'étudiant demande un feedback. 
Quand l'enseignant va pour répondre au feedback, il trouve la composante pour l'évaluation.
Si il procède à l'évaluation avant que l'étudiant le demande, c'est là qu'on a les boutons tout croches.
C'est une sitation un peu tordue, je ne voit pas ce qu'on peut faire pour ça...

![image](https://github.com/user-attachments/assets/b334f6c0-3178-4cb6-afc5-67f5bee21e66)

**Comment by olivier-gerbe** [comment]
J'ai corrigé.
J'ai ajouté une fonction testTextNotEmpty dans fonctions-kapc-commun14.js et modifier les menus des auto-evaluation-referentiel-bilan. Finaliser ne s'affiche que si la date de demande est renseignée.

**Comment by isabelle-roy** [comment]
Allo Olivier, j'ai pris le fichier kapc-commun sur notre serveur de dev, je l'ai mis sur notre serveur de test (ubs) et j'ai vidé ma cache. En tant qu'étudiante j'ai ajouté une nouvelle boite d'évaluation par l'enseignant et j'ai demandé un feedback. En tant qu'enseignant quand je répond au feedback j'ai encore le bouton Finaliser l'évaluation. Est-ce que tu peux regarder stp ?
Le compte enseignant c'est carron@univ-ubs.fr (via root) et la demande de feedback (compétence) c'est la question "mardi 14h40". Merci

**Comment by isabelle-roy** [comment]
Ok ça fonctionne

**Comment by AdrienPrugnaud** [comment]
C'est bon pour moi
@marusmb tu peux vérifier aussi stp
