### ISSUE TITLE
Message d'erreur lors de la création d'un stage quand on ajoute évaluation par un pair et tuteur pro en tant qu'admin

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#82]
J'ai eu ce message quand j'ai essayé de rajouter la section évaluation par un pair et un tuteur pro lors de la création d'un stage en tant qu'admin (cela fonctionne correctement pour l'auto-évaluation et l'évaluation par les enseignants)  :
![image](https://github.com/user-attachments/assets/04bcf768-2bd9-4699-a7c2-378cf85d2fc6)

![Bug stage](https://github.com/user-attachments/assets/17e89213-5f13-4797-8060-ee3676c9707b)

Tu peux vérifier en admin sur le serveur : https://test.recia.dev/recia-orleans pour la formation BUT Orléans Chimie

@isabelle-roy 
@olivier-gerbe

**Comment by isabelle-roy** [comment]
@olivier-gerbe 
Olivier ce message est affiché uniquement à un admin : pas à un auteur ni à un étudiant. 
Ça n'empêche pas l'import de la composante. 
Et il n'y a aucune erreur dans la console. 
Ça se produit uniquement pour les actions des répertoire de stage ou de SAé (composantes évaluations du module SAés) ; ça ne se produit pas pour les actions créées directement dans le portfolio étudiant (composantes évaluations actions du module étudiant). 
Je ne sais pas comment expliquer ce message ni l'empêcher.
Tu peux le voir en ajoutant une boite évaluation par le pair ou le tuteur dans un répertoire de stage ou de SAé en tant que root ; et comparer en ajoutant une boîte évaluation par le pair ou le tuteur dans une action autre d'un portfolio étudiant (par exemple celui de isabelle.roy).
Stp dis-moi si je dois ajouter par batch quelque chose quelque part.

**Comment by olivier-gerbe** [comment]
Pas réussi à reproduire

**Comment by isabelle-roy** [comment]
Je ne suis plus capable de reproduire non plus !
Peut-être qu'il fallait simplement vider la cache...

**Comment by AdrienPrugnaud** [comment]
je n'ai plus ce problème
