### ISSUE TITLE
Demandes invisibles concernant les feedbacks et les évaluations des compétences des portfolios migrés

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#83]
Sur les portfolios migrés je n'arrive pas à voir les demandes d'évaluations et les demandes de feedbacks au niveau des compétences, quand je clique sur les jumelles j'ai cela : 

![image](https://github.com/user-attachments/assets/65596699-e50a-4ae6-aea1-2f665e970271)

(par contre cela fonctionne bien pour les SAés ou pour les compétences personnalisées).

Je viens de voir qu'il y avait une différence de nom et prénom. Les demandes où il y a marqué "PAULINE VOILLOT" ne fonctionnent pas alors que pour les demandes de "VOILLOT PAULINE" (pourtant les demandes sont parties du même compte) : 
![image](https://github.com/user-attachments/assets/c0eaaeb1-1b61-4584-9de4-59ca13473bda)

https://test.recia.dev/recia-orleans

Tu peux prendre ce compte :
id : adrien.eure
mdp : demonumerique

@isabelle-roy 
@olivier-gerbe

**Comment by olivier-gerbe** [comment]
Cela vient du fait que le portfolio etudiant n'est pas partagé avec l'enseignant.
@isabelle-roy  Sais-tu quand se fait le partage du portfolio avec l'enseignant ?

**Comment by isabelle-roy** [comment]
Allo Adrien, est-ce que ça se peut que vous avez réinitialisé votre environnement de tests mais oublié de vider la table des vecteurs ? Isabelle

**Comment by AdrienPrugnaud** [comment]
@isabelle-roy 
Tout était réinitialisé pourtant, j'ai fait les demandes les unes après les autres.
Je viens de faire les demandes après avoir supprimer les vecteurs et rien n'y fait

https://github.com/user-attachments/assets/dcdfc287-7c36-4c7e-9587-93f049ba8b3b

**Comment by isabelle-roy** [comment]
@olivier-gerbe 
Je ne sais pas quoi dire, je n'ai pas ce problème. Le partage se fait au moment où l'enseignant clique sur la jumelle...

**Comment by isabelle-roy** [comment]
@AdrienPrugnaud 
Quand j'essaie de me connecter avec les infos que tu m'as données plus haut ça donne ça 

![image](https://github.com/user-attachments/assets/712cfb00-8277-4d26-a113-52c7f87232b4)

**Comment by AdrienPrugnaud** [comment]
@isabelle-roy 
Pas d'inquiétudes c'est normal, on vient de réinitialiser le serveur en prévision de la nouvelle livraison. Ton compte sera de nouveau actif demain (par contre le serveur sera en 1.3.5)

**Comment by AdrienPrugnaud** [comment]
@isabelle-roy je viens de refaire l'installation et j'ai le même problème (seulement pour les portfolios migrés et pour les compétences, pour les SAés cela fonctionne).

Voici les comptes utilisés : 
enseignant : 
id : adrien.eure

etudiant : 
id : marc.loire

Lien serveur : 
https://test.recia.dev/recia-orleans

**Comment by isabelle-roy** [comment]
@olivier-gerbe J'ai fait le test sur notre serveur de test et le portfolio de l'étudiant est partagé avec l'enseignant au moment où l'enseignant clique sur la jumelle

**Comment by olivier-gerbe** [comment]
Il ne faut pas faire les tests avec des portfolios importés. Le uuid du portfolio n'était pas bon dans la compétence à cause de l'importation. Nous avons fait un test avec une nouvelle compétence et c'est bon.

**Comment by AdrienPrugnaud** [comment]
Ok fonctionnel
