### ISSUE TITLE
Problèmes module Europass : langues étrangères

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#84]
Dans la section mes langues du projet de vie quand je veux supprimer certaines langue je suis déconnecté : 
A tester car le problème n'arrive pas tout le temps

![Langue](https://github.com/user-attachments/assets/8a53ad93-8093-478c-9f52-78e504c415a6)

https://test.recia.dev/recia-orleans

Tu peux prendre ce compte :
id : marc.loire
mdp : demonumerique

@isabelle-roy 
@olivier-gerbe

**Comment by isabelle-roy** [comment]
@olivier-gerbe 
Moi j'ai un problème différent avec les langues étrangères : à partir du moment où je clique sur le bouton pour en ajouter une, je perd les droits d'édition sur mon portfolio Projet de vie (pas sur mon portfolio d'APC). 
Les champs du module Europass sont encore éditables (user) mais tous les champs de rôle étudiant ne sont plus éditables (barre rouge en haut).

Tu peux tester ce que ça donne avec l'étudiant e2300333@univ-ubs.fr (via root) sur mon serveur de test ubs.

**Comment by olivier-gerbe** [comment]
C'est un effet de bord de la possibilité d'avoir plusieurs rôles dans un même portfolio.

J'a fait des modifications aux parts de Europass.

**Comment by isabelle-roy** [comment]
Ok de mon côté avec le nouveau module.
[europass-2024-09-14.zip](https://github.com/user-attachments/files/17003229/europass-2024-09-14.zip)

**Comment by marusmb** [comment]
Je viens de tester avec la version du 14-09, j'ai mis toutes les langues et je n'ai pas rencontré de problème.

**Comment by AdrienPrugnaud** [comment]
J'ai refait des tests et j'ai le même problème à rester avec le nouveau module
