### ISSUE TITLE
Création portfolio à la main dans Formulaire

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#86]
Dans le portfolio "Formulaire" quand je veux créer un portfolio avec l'authentification @externe j'ai un message d'erreur à la fin (mais pas quand je choisis l'authentification @karuta). 
Cela peut porter à confusion car les comptes et portfolios sont créés : 

https://github.com/user-attachments/assets/9688e7e2-73e4-4fc6-a615-ea190e558266

@olivier-gerbe 
@isabelle-roy

**Comment by isabelle-roy** [comment]
Ça c'est la nouvelle façon d'exécuter les batchs d'Olivier. Tu vas avoir ça dans tous tes batchs. Moi j'ignore tout ce qui est écrit après ===THIS IS THE END=== 

(Dans ce cas précis on fait un test pour savoir si c'est un compte externe ou karuta, et on branche dans les instructions selon que le test passe ou échoue. Dans d'autres cas tu vas créer un évaluateur par exemple et on va essayer de le supprimer du répertoire d'évaluateur pour ne pas avoir de doublon ; tu vas avoir une erreur là aussi. Tu vas régulièrement avoir des erreurs dans les batchs et ça fait partie du processus normal.)

**Comment by AdrienPrugnaud** [comment]
Pas de bug, nouveau fonctionnement
