### ISSUE TITLE
Menu Alternance en double

### ISSUE THREAD

**Issue by marusmb** [avenirs-esr/GT-Test#87]
Les enseignants ont deux fois le menu "Alternances".
![image](https://github.com/user-attachments/assets/a3180821-183e-45f7-bc5c-7defbfd4977f)

**Comment by isabelle-roy** [comment]
La seule façon que je peux voir que tu es arrivé là, c'est que le batch de migration a été exécuté deux fois sur les mêmes portfolios.

![image](https://github.com/user-attachments/assets/6cdef3f9-9851-4b63-b69e-bd0343b4a5f1)

**Comment by AdrienPrugnaud** [comment]
J'ai vérifié et je n'ai pas ce problème : 
![image](https://github.com/user-attachments/assets/bf84682e-4cb0-49c8-8ff4-ce033aa810ad)

**Comment by marusmb** [comment]
J'ai suivi les étapes décrites dans "Instructions migration de KAPC 1.3.5 à 1.4" les deux dernières étapes ont été particulièrement longues. Je n'ai peu être pas utilisé les bons zip, j'ai utilisé les plus récents que j'ai trouvé dans le répertoire l'espace de dépôt  "Module migration KAPC 1.3.5 à 1.4/2024-09-10".

**Comment by isabelle-roy** [comment]
Allo Michel,
C'est normal que ce soit trèèès long pour les portfolios enseignant et étudiants.
Je viens de voir qu'une de mes instances a le problème.
J'ai pas encore trouvé dans quel cas ça se produit mais je vais chercher.
Je te tiens au courant.
Isabelle

**Comment by isabelle-roy** [comment]
@marusmb 
Est-ce que c'est juste un portfolio ou c'est quelques uns ou c'est tous ?

**Comment by marusmb** [comment]
Ce n'est pas sur un seul portfolio, je l'ai vu sur les quelques enseignants que j'ai testés. Je vais voir sur un plus grand nombre.

**Comment by isabelle-roy** [comment]
@marusmb 
Bon je n'ai pas compris pourquoi il fait ça mais j'ai trouvé comment l'en empêcher alors j'ai ajouté un élément dans le batch de migration pour que ça ne se reproduise plus.
Ça sera livré avec la prochaine version.

**Comment by AdrienPrugnaud** [comment]
C'est bon pour moi
@marusmb A retester stp pour confirmation que tout fonctionne bien

**Comment by marusmb** [comment]
Tests sur la version du 25/09/2024, vérification sur au moins un enseignant de chaque formation. Problème non reproduit.
