### ISSUE TITLE
Problème script tableau synthèse page compétence

### ISSUE THREAD

**Issue by isabelle-roy** [avenirs-esr/GT-Test#88]
Allo Olivier, il y a un petit problème avec le nouveau script de tableau dans la page Compétence :
si quelqu'un ne renseigne aucun apprentissage critique, ça fait planter la boucle pour ce niveau de développement au complet ;
le niveau niveau n'est pas du tout affiché même si il est présent dans d'autres actions.
 
![image](https://github.com/user-attachments/assets/ede1a730-d887-418f-9592-0ead9578a759)

Pour voir :
sur notre serveur de test (ubs) portfolio de isabelle.roy, à la page Autres actions / test tableau synthèse, retire l'apprentissage critique : tout le niveau de développement va disparaître du tableau de synthèse à la page Compétences / BUT Génie Industriel / Maintenir en condition opérationnelle.

Normalement il devrait toujours y avoir des apprentissages critiques, mais on ne sait jamais ce que les profs vont essayer de faire avec l'outil... est-ce qu'il y a moyen de rendre le tableau plus robuste ?
Si oui, stp fait les corrections sur le serveur de test puis je le transférerai moi-même sur notre serveur de développement (je suis déjà en train de travailler la lisibilité). Merci

**Comment by olivier-gerbe** [comment]
C'était un problème de css. Nouveau fichier kapc14.css sur ubs et kapc14

**Comment by isabelle-roy** [comment]
Super, ça marche de mon côté !

**Comment by AdrienPrugnaud** [comment]
C'est bon pour nous aussi, à fermer
