### ISSUE TITLE
Problème création portfolio projet de vie par CSV pour étudiants créés sur la version 1.3.5

### ISSUE THREAD

**Issue by marusmb** [avenirs-esr/GT-Test#89]
Lors de la création des portfolios projet de vie par fichier CSV pour des étudiants ayant été créés avec la version 1.3.5, seul le premier étudiant est traité et quand on se connecte sur le compte de cet étudiant les deux portfolios apparaissent sur la page d'accueil.
![image](https://github.com/user-attachments/assets/893207f6-18a9-4d26-958d-1f5b082656bc)
[modèle csv créer étudiants projet de vie(6).csv](https://github.com/user-attachments/files/17060148/modele.csv.creer.etudiants.projet.de.vie.6.csv)

**Comment by isabelle-roy** [comment]
@olivier-gerbe 
Je viens d'exécuter son fichier csv (en modifiant les étudiants évidemment) sur notre serveur de test puis de tester les portfolios créés et tout se passe bien, à la fois à l'éxécution du batch et dans les comptes des étudiants.
Si tu as accès au serveur USMB est-ce que tu peux vois ce qui se passe ? Je ne me souviens plus des accès...

**Comment by AdrienPrugnaud** [comment]
Je n'ai pas eu ce problème (cohorte de 88 portfolio projet de vie créés)

**Comment by isabelle-roy** [comment]
Ok, moi non plus

**Comment by marusmb** [comment]
J'ai refait un essai et cette fois cela fonctionne, ci-joint mes 2 fichiers csv
[modèle csv créer étudiants projet de vie (Ok).csv](https://github.com/user-attachments/files/17074045/modele.csv.creer.etudiants.projet.de.vie.Ok.csv)
[modèle csv créer étudiants projet de vie(pb lors de la creéation des portfolio).csv](https://github.com/user-attachments/files/17074046/modele.csv.creer.etudiants.projet.de.vie.pb.lors.de.la.creeation.des.portfolio.csv)
