### ISSUE TITLE
Problème envoi mail - demander une évaluation par un pair/à mon tuteur pro - portfolio étudiant

### ISSUE THREAD

**Issue by MattLUnLille** [avenirs-esr/GT-Test#9]
Re-bonjour,

Je souhaiterai savoir s'il était normal que les boutons "demander une évaluation par un pair" ou "demander une évaluation à mon tuteur pro" - dans le portfolio étudiant : "Mes actions et traces" -> "Mes actions" -> "Mes stages et alternances" -> "Intitulé de mon stage ou de mon alternance (à modifier)" -> dans la partie "7. Évaluation de mon stage ou alternance" située tout en bas - ne permettent pas pour le moment d'envoyer un mail ?
![Capture d’écran 2023-07-20 114639](https://github.com/avenirs-esr/GT-Test/assets/139477155/f787f695-3fa7-41e2-bd58-f95eb20a6dea)
Et si cela doit fonctionner, est-ce que le destinataire de ce mail aura son profil créé parmi les usagers, ou bénéficiera-t-il juste d'une visibilité sur le portfolio de l'étudiant ?
Je vous en remercie d'avance , bon courage à vous

**Comment by isabelle-roy** [comment]
Une fois bien formaté Karuta doit répondre Le courriel a été envoyé.
Le courriel contient un hyperlien vers la page concernée du portfolio.
Un compte temporaire est créé, qui permet de voir uniquement la page partagée.

**Comment by jgribonvald** [comment]
@MattLUnLille j'ai un pb sur l'infra de test, mes ingénieurs systèmes m'ont fait une blague, le smtp n'est plus joignable. Il faut que je fasse régler ça.

**Comment by MattLUnLille** [comment]
Merci pour vos réponses et éclairages, @isabelle-roy et @jgribonvald. Dès que tu pourras régler cela en temps voulu, je le retesterai Julien.
