### ISSUE TITLE
Nouveauté partage ?

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#90]
Lorsque je demande une évaluation à un pair ou à un tuteur pro dans une SAé, après avoir actualisé la page, le bouton pour demander une évaluation disparaît. 
Est-ce que c'est le nouveau fonctionnement ? Car avant je pouvais refaire partir une demande ce qui était utile en cas d'erreur dans l'adresse mail ou bien de changement de tuteur : 

![image](https://github.com/user-attachments/assets/e492c10f-9ad9-4df7-b501-668fa4ef93df)

@olivier-gerbe 
@isabelle-roy

**Comment by olivier-gerbe** [comment]
Oui, c'est le nouveau fonctionnement. Cela a été demandé.

**Comment by AdrienPrugnaud** [comment]
D'accord merci
