### ISSUE TITLE
Bouton impression PDF projet de vie

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#91]
J'ai vu qu'il y avait la possibilité d'imprimer la page en PDF : 
![image](https://github.com/user-attachments/assets/ab82ecf1-a7b6-4258-a67d-bd421da8c701)

Mais cette option n'est pas présente sur toutes les pages du projet de vie. L'option est manquante sur la page "Explorer mon futur" et "Bâtir mon projet" les sous sections "Mes formations", "Mes expériences", "Mes langues".

@isabelle-roy 
@olivier-gerbe

**Comment by isabelle-roy** [comment]
On l'a mise là où Éric le voulait. J'imagine qu'il a une logique derrière ses choix. Ce n'est pas un oubli.

**Comment by isabelle-roy** [comment]
Par contre je suis d'accord que le bouton sur la page Faire mon bilan est inutile puisque cette page ne contient que des liens vers d'autres pages. Je vais le retirer. Ça va vouloir dire encore une nouvelle version du projet Karuta.

**Comment by isabelle-roy** [comment]
@giraudin 
Le bouton imprimante sur la page Faire mon bilan, est-ce que tu pensais que ça allait imprimer les pages qui sont à l'intérieur de la section ? Si c'était ça ton intention le bouton n'est pas à la bonne place et je dois le déplacer.
De toute façon je le retire de la page Faire mon bilan, ça ne sert à rien.
Tu me diras si tu veux que je le rajoute sur les pages qui sont à l'intérieur.
Mais moi j'avais compris que la seule page qu'on imprimait c'était le CV (Ma synthèse).
Isabelle

**Comment by AdrienPrugnaud** [comment]
@giraudin qu'en penses-tu ?
Soit on met le bouton partout soit on le met seulement pour la partie "Ma synthèse" ?

@isabelle-roy 
Pour ma part je serais partant de le mettre dans l'ensemble de ces parties : 
- **Me connaître** (le bouton est déjà présent)
- **Explorer mon futur :** 
![image](https://github.com/user-attachments/assets/a2508953-7c72-4891-990a-77db412c49f0)
- **Les 3 sous-sections de "Faire mon bilan" :** 
![image](https://github.com/user-attachments/assets/b9c4acba-6f5e-4b5f-ad64-3af2fb1c00f5)
- **Puis dans "Batîr mon projet"** : 
![image](https://github.com/user-attachments/assets/79da73c9-e35f-4ee8-acb2-336a35c4a175)
- **et pour finir dans "Ma synthèse"** (le bouton est déjà présent ici)

**Comment by isabelle-roy** [comment]
Allo Adrien, dans mon souvenir Éric voulait le bouton seulement pour Ma Synthèse - c'est une base de CV.
Si je l'ajoute ailleurs ça veut dire encore une nouvelle version de KAPC 1.4 à livrer et à tester. Je ne trouve pas que c'est une bonne idée. Isabelle

**Comment by olivier-gerbe** [comment]
On ne touche plus à rien. L'étudiant peut toujours faire un pdf d'une page avec le bouton imprimer du browser.

**Comment by AdrienPrugnaud** [comment]
Ok je ferme l'issue
