### ISSUE TITLE
Mauvais titre création étudiant dans le Formulaires Projet de vie

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#92]
Pour la création du portfolio étudiant ici : 
![image](https://github.com/user-attachments/assets/361addfc-064a-48ad-bc8c-1dc0d5b38041)

Le titre de la section est "Authentification" alors que l'on parle de la visibilité du portfolio APC : 
![image](https://github.com/user-attachments/assets/af710b59-8b55-466e-9177-f359f7e4b6bb)

(du coup on a pas besoin du choix de la méthode d'authentification car elle a déjà été choisie dans le portfolio APC ?)

@isabelle-roy

**Comment by isabelle-roy** [comment]
Corrigé :

![image](https://github.com/user-attachments/assets/4adccb00-ba71-47cb-a5ec-138edc09b508)

**Comment by AdrienPrugnaud** [comment]
Corrigé
