### ISSUE TITLE
Erreur frappe "Formulaires APC" 

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#94]
Dans le portfolio "Formulaires APC" puis "Soumettre les pages compétences des portfolios étudiants" il y a une erreur de frappe ici (il manque un t) : 

![image](https://github.com/user-attachments/assets/0d47403a-956b-4419-ad0c-348ff702c6c3)

@isabelle-roy

**Comment by olivier-gerbe** [comment]
Corrigé dans notre version

**Comment by AdrienPrugnaud** [comment]
Fait
