### ISSUE TITLE
Carrés gris synthèse des apprentissages critiques dans les parties bilans

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#95]
Dans la partie "Mes bilans par compétences", dans la "Synthèse des apprentissages critiques" pour les SAés on a les carrés gris qui sont rajoutés mais pas pour l'ensemble des autres actions (les stages, les autres actions...) : 
![image](https://github.com/user-attachments/assets/ac5ad6c0-ecdc-45a3-b95f-f1d94b58c904)

(pareil pour les bilans des compétences personnalisées) 

@isabelle-roy Est-ce que c'est normal ?
@giraudin Qu'est-ce que tu préfères Eric, avec carrés gris ou bien sans ?

**Comment by olivier-gerbe** [comment]
Corrigé dans notre version. Il y aura des carrés gris partout.

**Comment by AdrienPrugnaud** [comment]
Fait
