### ISSUE TITLE
Synthèse des apprentissages compétences personnalisées

### ISSUE THREAD

**Issue by AdrienPrugnaud** [avenirs-esr/GT-Test#96]
Je viens de rajouter un stage et une autre action avec une compétence personnalisée mais ces actions ne sont pas reprises dans la "Synthèse des apprentissages" de la partie des bilans :
![image](https://github.com/user-attachments/assets/0a773073-0731-44e9-afb4-7935b3dcc9c0)

![compétence perso](https://github.com/user-attachments/assets/d820ef3e-524c-4c28-b916-7210057f19be)

@isabelle-roy 
@olivier-gerbe

**Comment by olivier-gerbe** [comment]
Oups! Vraiment désolé. J'avais dû désactiver une partie lorsque j'ai travaillé sur le tableau de bord et oublié de réactiver la partie compétence personnalisée. Merci de t'en être rendu compte.
J'ai mis une nouvelle version sur NextCloud.

**Comment by AdrienPrugnaud** [comment]
Pas de soucis, corrigé
